{
  "hash": "3b433738f6d0cac251e5bdf18a6bbe79",
  "result": {
    "engine": "knitr",
    "markdown": "# Meta-Analysis for Evidence Synthesis {#sec-meta-analysis}\n\n\n\n## Introduction\n\nA single study, no matter how well designed, provides only one piece of evidence. **Meta-analysis** is the statistical method for combining results from multiple independent studies addressing the same question, producing a more precise and more generalisable estimate of an effect.\n\nAs a health researcher you will meet meta-analyses constantly: they underpin clinical guidelines, they settle (and unsettle) treatment decisions, and they are often the papers your colleagues cite at you. Whether you are running one or reading one, what matters is understanding *how* the numbers get combined and *what can go wrong* --- because when a meta-analysis is wrong, it is wrong with authority.\n\nThis chapter is deliberately narrow. It covers the core of an aggregate-data meta-analysis of a binary outcome, which is the overwhelming majority of what appears in clinical journals, and it covers it properly: how the pooling works, how to read a forest plot, how to think about heterogeneity, and how to detect the one failure mode that has misled clinical practice most often. @sec-meta-next-steps points you at the more specialised methods without pretending to teach them in a paragraph.\n\n::: {.callout-note}\n## Systematic review vs meta-analysis\nA **systematic review** is the process of comprehensively searching for, selecting, and appraising studies. A **meta-analysis** is the *statistical* component --- combining the numbers. You can have a systematic review without a meta-analysis (if the studies are too different to combine), but you should never have a meta-analysis without a systematic review.\n:::\n\nThe diagram below shows where the meta-analysis fits in the wider pipeline. Most of the work is finding and appraising studies; the statistical pooling is the final step.\n\n```{mermaid}\n%%| echo: false\n%%| eval: true\n%%| label: fig-pipeline\n%%| fig-cap: \"From research question to pooled estimate: the systematic-review-to-meta-analysis pipeline. Review and reporting steps follow the PRISMA 2020 statement [@page2021prisma].\"\nflowchart LR\n    A[Research question] --> B[Search the literature]\n    B --> C[Screen and select studies]\n    C --> D[Appraise quality<br/>risk of bias]\n    D --> E[Extract effect estimates]\n    E --> F[Meta-analysis:<br/>pool into one estimate]\n    F --> G[Forest plot,<br/>heterogeneity, bias checks]\n```\n\n## What a Meta-Analysis Combines\n\nEach study contributes an **effect estimate** --- a single number summarising how big the effect was (\"the drug cut the risk of stroke by 30%\") --- and a measure of its **precision**, meaning how confident we are in that number (a standard error or confidence interval). The meta-analysis computes a **weighted average**: rather than treating every study equally, it gives more precise studies more say. This is **inverse-variance weighting**, because each study's weight is one divided by its variance.\n\n$$\n\\hat{\\theta}_{\\text{pooled}} = \\frac{\\sum_{i=1}^{k} w_i \\hat{\\theta}_i}{\\sum_{i=1}^{k} w_i}\n$$\n\nwhere $\\hat{\\theta}_i$ is the effect estimate from study $i$, $w_i$ its weight, and $k$ the number of studies. In plain terms: a large, precise trial pulls the combined answer towards its own result more strongly than a small, imprecise one --- exactly as your intuition would suggest.\n\nHold on to that sentence. Almost everything that goes wrong in a meta-analysis is a disagreement about *how much* more say the big trials should get.\n\n## Effect Measures\n\nThe choice of effect measure depends on the type of outcome.\n\n**Binary outcomes** (died / did not die, event / no event):\n\n| Measure | Formula | When to use |\n|---|---|---|\n| **Risk ratio (RR)** | $\\frac{a/(a+b)}{c/(c+d)}$ | Cohort studies and trials; the most interpretable choice for clinicians |\n| **Odds ratio (OR)** | $\\frac{ad}{bc}$ | Case-control studies; logistic regression |\n| **Risk difference (RD)** | $\\frac{a}{a+b} - \\frac{c}{c+d}$ | When the absolute risk is what matters for a decision |\n\nHere $a, b, c, d$ are the cells of a 2x2 table (treatment events, treatment non-events, control events, control non-events). Ratios are pooled on the **log scale**, because their sampling distributions are roughly normal there, and back-transformed for presentation.\n\n**Continuous outcomes:**\n\n| Measure | Formula | When to use |\n|---|---|---|\n| **Mean difference (MD)** | $\\bar{X}_T - \\bar{X}_C$ | All studies use the same measurement scale |\n| **Standardised mean difference (SMD)** | $\\dfrac{\\bar{X}_T - \\bar{X}_C}{S_{\\text{pooled}}}$ | Studies use different scales for the same construct (e.g. different depression questionnaires) |\n\nHere $\\bar{X}_T$ and $\\bar{X}_C$ are the average outcomes in the treatment and control groups. $S_{\\text{pooled}}$ is the **pooled standard deviation**: how much patients within a group differ from one another, combined across the two arms.\n\n$$\nS_{\\text{pooled}} = \\sqrt{\\frac{(n_T - 1)\\,S_T^2 + (n_C - 1)\\,S_C^2}{n_T + n_C - 2}}\n$$\n\nwhere $n_T$ and $n_C$ are the two group sizes and $S_T$ and $S_C$ the standard deviations *within* each group. It is essentially a sample-size-weighted average of those two standard deviations --- not the standard deviation of the difference, and not the standard error.\n\nDividing by it is what makes different measurement scales comparable. Suppose one trial measured depression on a 0--63 questionnaire and improved scores by 6 points, while another used a 0--52 questionnaire and improved them by 4. Those raw numbers cannot be averaged together. But if patients within a group typically varied by 12 points on the first scale and 8 points on the second, then both trials moved patients by half of that typical variation, and the SMD is 0.5 in both. **The SMD expresses the effect in units of how much patients differ from each other**, so SMD = 0.5 means the average treated patient ended up half a standard deviation better off than the average control patient.\n\nThe cost is interpretability. \"Half a standard deviation\" is not a clinical quantity, and it depends on how variable the recruited population happened to be: a trial with narrow eligibility criteria has a small $S_{\\text{pooled}}$ and therefore reports a *larger* SMD for exactly the same real benefit. Use the plain mean difference whenever the studies share a scale.\n\nThe SMD is also known as **Hedges' g** (with a small-sample correction applied, which is the version you should use) or **Cohen's d** (without it).\n\n::: {.callout-warning}\n## The effect measure is not just a presentation choice\nIt changes which asymmetry tests are valid later (@sec-meta-nonreporting), and the odds ratio in particular has a mathematical quirk that makes the standard publication-bias test unreliable. Decide the measure from the clinical question, then pick methods that suit it --- not the other way round.\n:::\n\n## The Running Example: Magnesium After a Heart Attack {#sec-meta-example}\n\nEvery analysis in this chapter uses one real dataset, so that the methods can be compared on identical evidence.\n\nIn the 1980s and early 1990s, a series of randomised trials tested whether giving intravenous **magnesium** to patients having an acute myocardial infarction reduced mortality. Magnesium is cheap, widely available, and biologically plausible as a cardioprotective agent. Sixteen trials accumulated. They are shipped with `metafor` as `dat.egger2001`, taken from Table 18.2 of @egger2001systematic.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(metafor)   # for the dataset\nlibrary(tidyverse) # for the summary below\n\nmag <- dat.egger2001 |>\n  mutate(n_total = n1i + n2i)\n\n# ai / n1i = deaths / patients on magnesium; ci / n2i = deaths / patients on control\nmag |>\n  transmute(trial = paste(study, year), magnesium = paste0(ai, \"/\", n1i),\n            control = paste0(ci, \"/\", n2i), n_total) |>\n  arrange(n_total) |>\n  as.data.frame() |>\n  print(row.names = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             trial  magnesium    control n_total\n    Bertschat 1989       0/22       1/21      43\n Ceremuzynski 1989       1/25       3/23      48\n      Pereira 1990       1/27       7/27      54\n         Golf 1991       5/23      13/33      56\n       Morton 1984       1/40       2/36      76\n      Abraham 1987       1/48       1/46      94\n     Shechter 1989       1/59       9/56     115\n        Singh 1990       6/76      11/75     151\n     Shechter 1991       2/89      12/80     169\n     Shechter 1995      4/107     17/108     215\n    Thogersen 1991      4/130      8/122     252\n    Rasmussen 1986      9/135     23/135     270\n    Feldstedt 1988     10/150      8/148     298\n        Smith 1986      2/200      7/200     400\n      LIMIT-2 1992    90/1159   118/1157    2316\n       ISIS-4 1995 2216/29011 2103/29039   58050\n```\n\n\n:::\n:::\n\n\nLook at the right-hand column before reading on. Thirteen of the sixteen trials randomised fewer than 400 patients in total; the largest randomised 58,050 and accounts for 93% of all the patients ever studied. **That imbalance is the whole story of this chapter**, and it is typical rather than exceptional: most clinical literatures consist of many small studies and one or two large ones.\n\nWe will build up the standard analysis, and only in @sec-meta-nonreporting reveal what actually happened.\n\n## Fixed-Effect vs Random-Effects Models\n\nThe single most consequential choice in a meta-analysis is whether you assume the studies are all estimating *one* true effect or a *range* of true effects.\n\nThe next few pages use a handful of Greek symbols, so here is the whole vocabulary in one place. You can read the rest of the chapter with nothing more than this.\n\n::: {.callout-note}\n## The symbols in this chapter, in words\n\n| Symbol | Read it as | What it means here |\n|---|---|---|\n| $\\theta$ | \"theta\" | A **true effect** --- the answer we would get from an infinitely large, perfect study. Greek letters are for quantities that exist but are never observed. |\n| $\\hat{\\theta}$ | \"theta hat\" | An **estimate** of that effect, calculated from data actually collected. The hat always means \"our best guess at, from a sample\". |\n| $\\theta_i$, $\\hat{\\theta}_i$ | \"theta i\" | The true effect, and the estimate, **in study number $i$**. The subscript just numbers the studies. |\n| $k$ | \"k\" | The **number of studies** being pooled (here, 16). |\n| $\\hat{\\sigma}_i^2$ | \"sigma squared i\" | Study $i$'s **within-study variance**: how much its own result would bounce around if that same trial were repeated. It is the square of the standard error, so a big trial has a *small* $\\hat{\\sigma}_i^2$. |\n| $\\tau^2$, $\\hat{\\tau}^2$ | \"tau squared\" | The **between-study variance**: how much the true effects genuinely differ from one study to the next. |\n| $\\mu$ | \"mu\" | The **average** of the true effects across studies --- what a random-effects model is actually estimating. |\n| $w_i$ | \"w i\" | The **weight** given to study $i$ when averaging. |\n| $\\theta_i \\sim N(\\mu, \\tau^2)$ | \"theta i is normally distributed with mean mu and variance tau squared\" | The true effects are scattered in a bell curve centred on $\\mu$, whose width is $\\tau$. |\n\nWhenever a formula looks opaque, read the hats as \"estimated\", the subscript $i$ as \"for this one study\", and $\\sigma$ and $\\tau$ as \"noise within a study\" and \"real differences between studies\". [Appendix B](../appendices/B_math_notation.qmd) has a fuller list for the rest of the book.\n:::\n\n**The fixed-effect model** assumes every study estimates the **same** true effect $\\theta$; differences between results are pure sampling noise, like getting slightly different averages each time you measure the same group of patients. Weights are the inverse of the within-study variance:\n\n$$\nw_i^{\\text{FE}} = \\frac{1}{\\hat{\\sigma}_i^2}\n$$\n\nIn words: **a study's weight is one divided by how noisy it is.** Halve a study's standard error --- which takes roughly four times as many patients --- and you quadruple its weight, because the variance is the standard error squared.\n\n**The random-effects model** assumes each study estimates **its own** true effect $\\theta_i$, and that these scatter around an overall average: $\\theta_i \\sim N(\\mu, \\tau^2)$. In plain terms, the treatment might genuinely work better in one population than another, so there is no single true number to find; there is an average, and a spread around it. Weights add the between-study variance:\n\n$$\nw_i^{\\text{RE}} = \\frac{1}{\\hat{\\sigma}_i^2 + \\hat{\\tau}^2}\n$$\n\nIn words: **a study's weight is now one divided by (how noisy it is *plus* how much studies really differ).** The second term is the same for every study, because it is a property of the literature rather than of any one trial.\n\n$\\tau^2$ (**tau-squared**) is that second term: how much the true effects genuinely scatter, over and above sampling noise. It is estimated from how widely the observed results disagree, after allowing for the noise you would expect anyway. If $\\tau^2 = 0$ --- the studies agree no more and no less than chance predicts --- the random-effects model collapses back to the fixed-effect one.\n\n::: {.callout-note}\n## How this relates to mixed models, and one terminology trap\n\nIf this feels like @sec-mixed-models, that is because it is the same machinery. A random-effects meta-analysis is a mixed model in which each **study** plays the part of a cluster, $\\tau^2$ is the between-cluster variance, and the within-cluster variances $\\hat{\\sigma}_i^2$ are taken as already known rather than estimated from raw patient data. Partial pooling is what the weights $w_i^{\\text{RE}}$ are doing, and $I^2$ (below) has the same shape as the intraclass correlation: between-variance over total variance. @sec-meta-bayesian fits precisely that model, with the same `(1 | cluster)` syntax the mixed-models chapter used for clinics.\n\nThe trap is the word \"fixed\". In a mixed model, **fixed effects** are the population-average coefficients you care about, and they sit *alongside* random effects in the same model. In meta-analysis, the **fixed-effect model** is a *rival* to the random-effects model, meaning \"assume one single true effect for all studies\". Same word, unrelated meaning --- which is part of why Cochrane writes \"fixed-effect\" in the singular for this sense.\n:::\n\n::: {.callout-important}\n## Adding $\\hat\\tau^2$ to every study levels the weights --- and that cuts both ways\n\nLook at what $w_i^{\\text{RE}}$ does. A large trial has a tiny $\\hat{\\sigma}_i^2$, so adding $\\hat{\\tau}^2$ to it changes its weight enormously in relative terms. A small trial's $\\hat{\\sigma}_i^2$ is already large, so adding $\\hat{\\tau}^2$ barely changes it. The net effect is that **small studies gain influence and large studies lose it.**\n\nWhen the studies genuinely differ, that is correct behaviour: you should not let one mega-trial in one population speak for all populations. When the small studies are *biased*, it is a disaster, because the model hands the analysis to precisely the studies you should trust least.\n:::\n\nThat is not an abstract worry. Here are both models on the magnesium data:\n\n::: {.panel-tabset}\n\n### R\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(meta)   # metabin(), forest(), funnel(), metabias()\n\n# Modern defaults, and why:\n#   method.tau = \"REML\"      -- REML (or Paule-Mandel) estimates tau^2 better than\n#                               the older DerSimonian-Laird default (Veroniki 2016)\n#   method.random.ci = \"HK\"  -- Hartung-Knapp-Sidik-Jonkman interval, which has\n#                               much better coverage than the normal-based one,\n#                               especially with few studies (IntHout 2014)\n#   prediction = TRUE        -- always report a prediction interval (Riley 2011)\nm <- metabin(\n  event.e = ai, n.e = n1i,        # magnesium arm\n  event.c = ci, n.c = n2i,        # control arm\n  studlab = paste(study, year),\n  data = dat.egger2001,\n  sm = \"RR\",\n  method.tau = \"REML\",\n  method.random.ci = \"HK\",\n  prediction = TRUE\n)\n\nrr <- function(x) sprintf(\"%.3f\", exp(x))\ncat(\"FIXED-EFFECT  RR:\", rr(m$TE.common),\n    sprintf(\"(95%% CI %s to %s)\\n\", rr(m$lower.common), rr(m$upper.common)))\ncat(\"RANDOM-EFFECTS RR:\", rr(m$TE.random),\n    sprintf(\"(95%% CI %s to %s)\\n\", rr(m$lower.random), rr(m$upper.random)))\ncat(sprintf(\"tau^2 = %.3f | I^2 = %.1f%% | Q test p = %.4f\\n\",\n            m$tau2, 100 * m$I2, m$pval.Q))\ncat(\"PREDICTION interval:\", rr(m$lower.predict), \"to\", rr(m$upper.predict), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFIXED-EFFECT  RR: 1.006 (95% CI 0.952 to 1.062)\nRANDOM-EFFECTS RR: 0.511 (95% CI 0.356 to 0.735)\ntau^2 = 0.227 | I^2 = 66.7% | Q test p = 0.0001\nPREDICTION interval: 0.171 to 1.526 \n```\n\n\n:::\n:::\n\n\n### Python\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.python .cell-code}\nimport numpy as np\nfrom scipy import stats\n\n# The same 16 trials: deaths / patients on magnesium, then on control\nai = np.array([1, 9, 2, 1, 10, 1, 1, 0, 6, 1, 2, 5, 4, 90, 4, 2216])\nn1 = np.array([40, 135, 200, 48, 150, 59, 25, 22, 76, 27, 89, 23, 130, 1159, 107, 29011])\nci = np.array([2, 23, 7, 1, 8, 9, 3, 1, 11, 7, 12, 13, 8, 118, 17, 2103])\nn2 = np.array([36, 135, 200, 46, 148, 56, 23, 21, 75, 27, 80, 33, 122, 1157, 108, 29039])\n\n# Continuity correction: add 0.5 ONLY to the trial that has a zero cell\n# (Bertschat 1989 had 0 deaths on magnesium). This is what metabin() does by\n# default -- correcting every study instead would shift all the estimates.\nzero = (ai == 0) | (ci == 0)\nincr = np.where(zero, 0.5, 0.0)\na, c = ai + incr, ci + incr\nb, d = n1 - ai + incr, n2 - ci + incr\nlog_rr = np.log((a / (a + b)) / (c / (c + d)))\nvar = 1 / a - 1 / (a + b) + 1 / c - 1 / (c + d)\n\n# --- fixed effect: weight = 1 / within-study variance -----------------------\nw_fe = 1 / var\nte_fe = np.sum(w_fe * log_rr) / np.sum(w_fe)\nse_fe = np.sqrt(1 / np.sum(w_fe))\n\n# --- between-study variance (DerSimonian-Laird, shown because it is the one\n#     you can compute by hand; REML is preferred in practice) ----------------\nk = len(log_rr)\nQ = np.sum(w_fe * (log_rr - te_fe) ** 2)\nC = np.sum(w_fe) - np.sum(w_fe ** 2) / np.sum(w_fe)\ntau2 = max(0.0, (Q - (k - 1)) / C)\nI2 = max(0.0, (Q - (k - 1)) / Q)\n\n# --- random effects: weight = 1 / (within + between) ------------------------\nw_re = 1 / (var + tau2)\nte_re = np.sum(w_re * log_rr) / np.sum(w_re)\nse_re = np.sqrt(1 / np.sum(w_re))\n\n# Hartung-Knapp-Sidik-Jonkman: rescale the SE and use a t distribution\nq_hk = np.sum(w_re * (log_rr - te_re) ** 2) / (k - 1)\nse_hk = np.sqrt(q_hk / np.sum(w_re))\nt_crit = stats.t.ppf(0.975, k - 1)\n\nprint(f\"FIXED-EFFECT  RR: {np.exp(te_fe):.3f} \"\n      f\"(95% CI {np.exp(te_fe - 1.96*se_fe):.3f} to {np.exp(te_fe + 1.96*se_fe):.3f})\")\nprint(f\"RANDOM-EFFECTS RR: {np.exp(te_re):.3f} \"\n      f\"(95% CI {np.exp(te_re - t_crit*se_hk):.3f} to {np.exp(te_re + t_crit*se_hk):.3f})\")\nprint(f\"tau^2 = {tau2:.3f} | I^2 = {100*I2:.1f}% | Q = {Q:.1f}, \"\n      f\"p = {1 - stats.chi2.cdf(Q, k - 1):.4f}\")\n\n# prediction interval: uncertainty in the mean PLUS genuine between-study spread\npi_se = np.sqrt(se_hk ** 2 + tau2)\nprint(f\"PREDICTION interval: {np.exp(te_re - stats.t.ppf(0.975, k-2)*pi_se):.3f} \"\n      f\"to {np.exp(te_re + stats.t.ppf(0.975, k-2)*pi_se):.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFIXED-EFFECT  RR: 1.014 (95% CI 0.959 to 1.071)\nRANDOM-EFFECTS RR: 0.530 (95% CI 0.371 to 0.758)\ntau^2 = 0.174 | I^2 = 66.7% | Q = 45.1, p = 0.0001\nPREDICTION interval: 0.202 to 1.391\n```\n\n\n:::\n:::\n\n\n:::\n\n**Read the two lines of output against each other.** This is not a subtle difference:\n\n| Model | Pooled risk ratio | Reading |\n|---|---|---|\n| Fixed effect | **1.006** (0.952 to 1.062) | Magnesium does nothing |\n| Random effects | **0.511** (0.356 to 0.735) | Magnesium halves mortality |\n\nSame sixteen trials, same outcome, same effect measure. One model says a cheap intravenous drug has no effect on death after a heart attack; the other says it prevents roughly one death in every two that would have occurred. If you have ever wondered whether the fixed-versus-random choice is a technicality, this is your answer.\n\nThe reason is exactly the mechanism in the callout above. Under the fixed-effect model the one 58,050-patient trial dominates, because weights are inverse-variance and its variance is minuscule. Under random effects, adding $\\hat{\\tau}^2 = 0.227$ to every study levels the weights, the thirteen small trials collectively outvote it, and they were nearly all positive.\n\n::: {.callout-tip}\n## So which do you report?\nRandom effects, in nearly all clinical settings --- studies really do differ in populations, doses, and outcome definitions, and the fixed-effect model's assumption is rarely defensible. But **report both when they disagree materially**, and treat the disagreement as a finding in its own right rather than a nuisance. A large fixed-versus-random gap is a signal that the small and large studies are telling different stories, which is the subject of @sec-meta-nonreporting.\n\nThe Python tab above hand-rolls the arithmetic because it is worth seeing once. Python's meta-analysis ecosystem is genuinely thin, though; for meta-analysis specifically R is the right tool, and we would rather say so than pretend otherwise.\n:::\n\n::: {.callout-note}\n## Why the two tabs print slightly different numbers\n\nThey are not inconsistent --- they differ by exactly two documented method choices, and it is worth knowing which, because you will meet both in published papers.\n\n| | R (`metabin` defaults) | Python (hand-rolled above) |\n|---|---|---|\n| Fixed-effect estimate | **Mantel-Haenszel**: 1.006 | **Inverse-variance**: 1.014 |\n| $\\tau^2$ estimator | **REML**: 0.227 | **DerSimonian-Laird**: 0.174 |\n| Random-effects RR | 0.511 | 0.530 |\n\nFor binary outcomes `metabin` defaults to **Mantel-Haenszel** for the fixed-effect estimate, which behaves better than inverse-variance when events are rare or cells are sparse. And REML estimates $\\tau^2$ larger than DerSimonian-Laird here, which is the expected direction: DL is known to underestimate between-study variance [@veroniki2016methods], and since $\\tau^2$ drives both the random-effects weights and the prediction interval, that difference propagates.\n\nYou can confirm the two implementations agree by making R match Python's choices:\n\n```r\nmetabin(ai, n1i, ci, n2i, data = dat.egger2001, sm = \"RR\",\n        method = \"Inverse\", method.tau = \"DL\",\n        method.random.ci = \"HK\", prediction = TRUE)\n#> fixed 1.014, random 0.530, tau^2 0.174, prediction 0.202 to 1.392\n```\n\nwhich reproduces the Python output to three decimal places. **Report your $\\tau^2$ estimator and your fixed-effect method.** Two papers pooling the same trials can differ by this much on defaults alone.\n:::\n\n## Reading a Forest Plot\n\nThe **forest plot** is the one figure almost every systematic review puts front and centre, and the one you most need to read fluently. @fig-forest-schematic labels the parts on a deliberately simple, invented example.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![How to read a forest plot. Each row is one study: the box marks its effect estimate and its **area** is that study's weight, the whisker is the 95% confidence interval. The vertical grey line is the no-effect line (a risk ratio of 1, meaning treatment and control fared identically); a whisker crossing it means that study alone cannot rule out no effect. The diamond is the pooled estimate. The red bar is the prediction interval --- the range in which a *new* study's true effect would be expected to fall. It is wider than the pooled confidence interval because it carries a second source of uncertainty on top of the first: not just *how precisely we know the average effect*, but *how much the true effect genuinely varies from setting to setting*. @sec-meta-prediction-interval works through the formula. It is the number to look at when deciding whether a result will transfer to your own patients.](meta_analysis_files/figure-html/fig-forest-schematic-1.png){#fig-forest-schematic fig-align='center' width=100%}\n:::\n:::\n\n\nSix things to check, in this order:\n\n1. **Where is the diamond, and does it cross the null line?** That is the headline.\n2. **Where is the prediction interval?** If it crosses the null while the diamond does not, the average effect is positive but a new setting could easily see nothing.\n3. **Are the big boxes and the small boxes on the same side?** If the large trials sit near the null and the small ones sit far from it, stop and read @sec-meta-nonreporting before believing the diamond.\n4. **Do the whiskers overlap?** Non-overlapping intervals mean the studies genuinely disagree.\n5. **Is one box doing all the work?** A single dominant trial means you have one trial with decoration, not a meta-analysis.\n6. **Heterogeneity statistics**, which the plot usually prints along the bottom.\n\nNow the real thing:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nforest(m,\n  sortvar = TE,\n  prediction = TRUE,\n  label.left = \"Favours magnesium\",\n  label.right = \"Favours control\",\n  col.diamond = \"#4a76a8\",\n  col.square = \"#2c3e50\",\n  print.tau2 = TRUE, print.I2 = TRUE, print.pval.Q = TRUE,\n  leftlabs = c(\"Trial\", \"Deaths\", \"Total\", \"Deaths\", \"Total\")\n)\n```\n\n::: {.cell-output-display}\n![The sixteen magnesium trials, sorted by effect size. Note the shape: the small trials (tiny boxes) cluster to the left of the null line, while the single large trial (the big box) sits astride it. The pooled diamond is dragged left by weight of numbers.](meta_analysis_files/figure-html/fig-forest-magnesium-1.png){#fig-forest-magnesium fig-align='center' width=100%}\n:::\n:::\n\n\n**What to notice.** Apply check 3 from the list. Fourteen of the fifteen smaller trials sit left of the null line --- several of them far left, with risk ratios of 0.11 to 0.24 --- while the one very large trial sits astride it at 1.05. That pattern, effect size shrinking as trials get bigger, has a name: **small-study effects**. It is the single most useful thing a forest plot can show you.\n\n`meta` also prints two weight columns, and they are worth a moment. ISIS-4 carries **89.8%** of the weight under the common-effect model and **15.9%** under random effects. The mechanism from the callout above is right there in the output: the same trial, the same data, an 80-percentage-point swing in influence purely from adding $\\hat{\\tau}^2$ to the denominator.\n\n## Heterogeneity: What Actually Varies {#sec-meta-heterogeneity}\n\n**Heterogeneity** means the studies disagree more than chance alone would explain. A tidy pooled estimate can hide wide disagreement underneath, so quantifying it tells you how much to trust the average.\n\nThree statistics get reported, and they answer three genuinely different questions. Confusing them is the most common error in the meta-analysis literature [@borenstein2024mistakes].\n\n| Statistic | The question it answers | What it is *not* |\n|---|---|---|\n| **Cochran's $Q$** (and its p-value) | *Is there any real variation at all?* A hypothesis test. | Not a measure of how much variation there is. Underpowered with few studies; over-powered with many. |\n| **$I^2$** | *What proportion of the observed scatter is real rather than sampling noise?* | **Not** how much the effect varies. A relative quantity: it can be 90% with trivial variation, or 0% with large variation, depending on how precise the studies are. |\n| **$\\tau^2$ / $\\tau$** | *How much do the true effects vary?* An absolute measure, on the effect scale. | Hard to interpret directly on a log scale. |\n\nAll three are built from one quantity, $Q$, so it is worth taking that apart slowly.\n\n$$\n\\underbrace{Q}_{\\substack{\\text{total observed} \\\\ \\text{disagreement}}}\n\\;=\\; \\sum_{i=1}^{k}\n\\underbrace{w_i^{\\text{FE}}}_{\\substack{\\text{precise studies} \\\\ \\text{count for more}}}\n\\times\n\\underbrace{\\left(\\hat{\\theta}_i - \\hat{\\theta}_{\\text{FE}}\\right)^2}_{\\substack{\\text{squared distance from} \\\\ \\text{the pooled estimate}}}\n$$\n\nTerm by term:\n\n- $(\\hat{\\theta}_i - \\hat{\\theta}_{\\text{FE}})^2$ is how far study $i$ landed from the pooled result, squared --- so that falling short and overshooting both count as disagreement.\n- Multiplying by $w_i^{\\text{FE}} = 1/\\hat{\\sigma}_i^2$ says that a *precise* study sitting far from the pooled estimate is more surprising than an imprecise one doing the same. Each term is therefore a distance measured in units of that study's own noise.\n- That scaling is what makes $Q$ interpretable. If every study really were estimating the same effect, each term would average about 1, so the whole sum would average about $k - 1$ (one degree of freedom goes on estimating the pooled effect itself). **So compare $Q$ with $k-1$: the excess is disagreement that sampling noise cannot account for.** On the magnesium data $Q = 45.1$ against $k - 1 = 15$ --- three times what noise alone would produce, hence $p = 0.0001$.\n\nBoth summary statistics are then built from that same excess, $Q - (k-1)$:\n\n$$\nI^2 = \\frac{\\overbrace{Q - (k-1)}^{\\text{excess over noise}}}{\\underbrace{Q}_{\\text{total disagreement}}} \\times 100\\%\n\\qquad\\qquad\n\\hat{\\tau}^2 = \\frac{\\overbrace{Q - (k-1)}^{\\text{excess over noise}}}{\\underbrace{C}_{\\substack{\\text{scaling constant} \\\\ \\text{(see below)}}}}\n$$\n\nwhere $C = \\sum_i w_i - \\left(\\sum_i w_i^2 \\big/ \\sum_i w_i\\right)$, and both quantities are set to zero if the excess comes out negative, which sampling noise alone can produce. (This is the DerSimonian-Laird version of $\\hat{\\tau}^2$, the one you can compute by hand; REML, which is preferred, solves for it iteratively instead.)\n\n**Same numerator, different denominators --- and that is the entire distinction between the two.** Dividing the excess by $Q$ gives a *proportion*: what share of the disagreement we can see is real rather than noise (66.7% here). Dividing it instead by $C$ rescales the excess into a *variance on the effect scale* (0.174 by this formula, 0.227 by REML), which is an amount rather than a share. This is why $I^2$ can be large when the true effects barely differ and small when they differ a lot: recruit ten times as many patients per trial and $Q$ --- the denominator --- grows, so $I^2$ rises, without the true effects having moved at all.\n\n::: {.callout-important}\n## $I^2$ does not tell you how much the effect varies\n\nYou will see the 25% / 50% / 75% \"low / moderate / high\" thresholds everywhere, including in @higgins2003inconsistency where they were offered as tentative rules of thumb. Current methodological guidance is blunt about them: classifications of heterogeneity based on $Q$, its p-value, or $I^2$ are \"uninformative at best, and often misleading\" [@borenstein2024mistakes; @borenstein2023heterogeneity].\n\nThe reason is that $I^2$ is a **ratio**, not an amount. It is the share of observed scatter that is real rather than noise. Run the same trials with ten times as many patients each and the sampling noise shrinks, so $I^2$ rises --- without the true effects having moved at all.\n\nThe statistic that answers \"how much does the effect vary?\" is the **prediction interval**. Report it. Use $I^2$, if at all, only to say what fraction of the scatter is signal.\n:::\n\n### The prediction interval {#sec-meta-prediction-interval}\n\nThe confidence interval describes the *average* true effect. The **prediction interval** answers the question a clinician actually has: if this treatment were used in a new setting tomorrow, what range of true effects might we see?\n\n$$\n\\underbrace{\\hat{\\mu}}_{\\substack{\\text{estimated average} \\\\ \\text{true effect}}} \\;\\pm\\; \\underbrace{t_{k-2,\\,0.975}}_{\\substack{\\text{multiplier, } k-2 \\text{ degrees}\\\\ \\text{of freedom (we estimated}\\\\ \\text{both } \\mu \\text{ and } \\tau^2)}} \\times \\underbrace{\\sqrt{\\underbrace{\\text{SE}(\\hat{\\mu})^2}_{\\substack{\\text{we are unsure} \\\\ \\text{of the average}}} + \\underbrace{\\hat{\\tau}^2}_{\\substack{\\text{settings genuinely} \\\\ \\text{differ}}}}}_{\\substack{\\text{total spread of a new} \\\\ \\text{setting's true effect}}}\n$$\n\nRead it as three pieces.\n\n$\\hat{\\mu}$, the centre, is just the random-effects pooled estimate --- the same number the confidence interval is built around. A prediction interval is not a different estimate; it is the same estimate with a wider ruler.\n\nThe **square-root term is where the intuition lives.** There are two independent reasons a new setting's true effect might not equal $\\hat{\\mu}$: we do not know $\\mu$ exactly (that is $\\text{SE}(\\hat{\\mu})^2$), *and* the truth genuinely differs from place to place even if we did know $\\mu$ (that is $\\hat{\\tau}^2$). Independent uncertainties add as variances, not as widths --- the same reason a journey made of two uncertain legs is less uncertain than the sum of its two worst cases --- so the two terms are added under the square root rather than added directly. A useful consequence: whichever term is much the larger dominates. Here $\\text{SE}(\\hat{\\mu})^2 = 0.036$ against $\\hat{\\tau}^2 = 0.227$, so roughly six-sevenths of the width comes from genuine between-setting variation, not from our ignorance about the average.\n\nThe **$t$ multiplier** plays the role that 1.96 plays in an ordinary confidence interval, but it is larger, because $\\hat{\\tau}^2$ is itself an estimate from only $k$ studies. With 16 trials it is 2.15 rather than 1.96; with 5 trials it would be 3.18. Few studies means an untrustworthy estimate of how much settings differ, and the multiplier says so.\n\nThe extra $\\hat{\\tau}^2$ under the square root is the whole point, and it is why the prediction interval in @fig-forest-schematic is drawn wider than the diamond: the confidence interval shrinks towards zero width as you add studies, because $\\text{SE}(\\hat{\\mu})$ does, but the prediction interval does not, because real between-setting variation does not go away no matter how precisely you measure it [@riley2011interpretation; @inthout2016prediction]. An infinite number of studies would tell you the average effect exactly and still leave you unsure what the next hospital will see.\n\n::: {.callout-note}\n## Which prediction-interval formula your software uses\nThe form above is the original one [@riley2011interpretation], and it is what the Python tab computes by hand. `meta` 8.x defaults to a refinement (`method.predict = \"V\"`) that uses $k-1$ degrees of freedom and a slightly different variance for $\\hat{\\mu}$, on the grounds of better coverage [@partlett2017random]. On these data the two agree closely --- 0.170 to 1.536 versus 0.171 to 1.526 --- and the choice between them matters far less than reporting an interval at all. Say which you used.\n:::\n\nFor the magnesium data:\n\n| | |\n|---|---|\n| $\\tau^2$ | 0.227 (so $\\tau = 0.48$ on the log-RR scale --- substantial) |\n| $I^2$ | 66.7% |\n| $Q$ test | p = 0.0001 |\n| Pooled RR (random effects) | 0.511 (95% CI 0.356 to 0.735) |\n| **Prediction interval** | **0.171 to 1.526** |\n\nRead the last two rows together. The confidence interval says the *average* effect is a clear benefit. The prediction interval **includes 1** --- so on this evidence, a new trial could plausibly find magnesium halves mortality, or that it does nothing, or that it causes modest harm. A guideline committee shown only the confidence interval would draw a very different conclusion from one shown both.\n\n## Investigating Heterogeneity\n\nWhen heterogeneity is substantial, the useful question is not \"how big is $I^2$\" but \"*what* differs between these studies?\" A characteristic that might explain the differences is called a **moderator**. It is a property of the *study*, not of an individual patient: the year the trial ran, the dose used, the average age of the population it recruited, its risk-of-bias rating.\n\nThere are two ways to test a moderator, and they are one idea applied to two kinds of variable.\n\n**Subgroup analysis** is for a *categorical* moderator. Split the studies into groups --- trials in hospital settings versus trials in primary care, high dose versus low dose --- pool each group separately, then test whether the group estimates differ by more than chance. It answers: *does the effect differ between these kinds of study?*\n\n**Meta-regression** is for a *continuous* moderator. Rather than splitting, it fits a weighted straight line across the studies, with the moderator on the horizontal axis and each study's effect estimate on the vertical, again giving precise studies more say. The slope says how much the effect changes per unit of the moderator --- \"the log risk ratio rose by 0.05 for each later calendar year\". It answers: *does the effect trend with this quantity?*\n\nThe two are faces of the same model: a subgroup analysis with two groups **is** a meta-regression on a 0/1 indicator, and the test for a subgroup difference is the test of that indicator's slope. Choose subgroups when the moderator really is categorical, and meta-regression when chopping a continuous variable at an arbitrary cut-point would throw information away --- the same argument @sec-splines makes for patient-level data.\n\nTwo constraints on both. They should be **pre-specified**: with a handful of studies and a free choice of moderator, you will always find something. And you have far less power than the patient counts suggest, because the unit of analysis is the *study*, not the patient --- 16 trials give you 16 data points for the line. A common rule of thumb is at least ten studies per moderator examined [@cochrane2024handbook].\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(meta)\nlibrary(metafor)\n\n# --- meta-regression on calendar year -------------------------------------\nes <- escalc(measure = \"RR\", ai = ai, n1i = n1i, ci = ci, n2i = n2i,\n             data = dat.egger2001)\nmr <- rma(yi, vi, mods = ~ I(year - 1984), data = es, method = \"REML\")\ncat(sprintf(\"year slope: %+.4f log RR per year, p = %.3f, R^2 = %.0f%%\\n\",\n            mr$beta[2], mr$pval[2], mr$R2))\n\n# --- subgroup analysis by trial size --------------------------------------\nes$size <- ifelse(es$n1i + es$n2i < 400, \"small (<400)\", \"large (>=400)\")\nm_sub <- update(m, subgroup = es$size)\nm_sub\n```\n:::\n\n\n**What the code shows and what it finds.** The meta-regression asks whether the effect drifted over calendar time: the slope is $+0.052$ log-RR per year with **p = 0.37**, explaining only 13% of the heterogeneity. On its own that is a null result, and it would be easy to report it as \"no evidence of a time trend\" and move on.\n\nSplitting by trial size instead tells a different story:\n\n| Subgroup | Trials | Pooled RR (random effects) |\n|---|---|---|\n| Small (<400 patients) | 13 | 0.423 (0.284 to 0.630) |\n| Large ($\\ge$400 patients) | 3 | 0.869 (0.362 to 2.085) |\n| *Test for subgroup difference* | | *p = 0.0085* |\n\nThe small trials say magnesium more than halves mortality. The large trials say it probably does nothing. And these two moderators are entangled --- the large trials are also the later ones --- which is why the year analysis picked up a weak, non-significant signal for what is really a size effect. **A non-significant moderator does not mean there is no explanation for the heterogeneity; it can mean you chose the wrong moderator.**\n\n::: {.callout-warning}\n## Two cautions on this subgroup analysis\n\nFirst, the honest one: splitting by trial size is a **diagnostic**, not a pre-specified subgroup analysis. Size is not a patient characteristic and there is no clinical hypothesis attached to it. It belongs in the small-study-effects investigation below, not in the results table as a subgroup finding.\n\nSecond, the **ecological fallacy**. Study-level associations do not imply individual-level ones. If trials with older populations show larger effects, that does *not* establish that older individuals benefit more --- the trials may differ in a dozen other ways. This is a fundamental limitation of aggregate-data meta-analysis, and the reason individual participant data (@sec-meta-next-steps) is worth the effort when the question is about who benefits.\n:::\n\n## Bayesian Meta-Analysis {#sec-meta-bayesian}\n\nYou have already met everything needed for this. A random-effects meta-analysis **is** a hierarchical model --- statisticians call this particular one the normal-normal hierarchical model --- which is exactly the object @sec-bayesian-inference introduced, so the Bayesian version is not a new method. It is the same two lines of model, fitted the way that chapter fitted things [@sutton2001bayesian].\n\nWritten out, the model is:\n\n$$\n\\underbrace{\\hat{\\theta}_i \\sim N(\\theta_i,\\; \\hat{\\sigma}_i^2)}_{\\substack{\\text{what we observe: each study's estimate} \\\\ \\text{scatters around its own true effect}}}\n\\qquad\\qquad\n\\underbrace{\\theta_i \\sim N(\\mu,\\; \\tau^2)}_{\\substack{\\text{what we assume: the true effects} \\\\ \\text{scatter around an average}}}\n$$\n\nThe second line is the random-effects assumption from earlier in this chapter, unchanged. The difference is what happens to $\\mu$ and $\\tau$. The frequentist route estimates $\\tau^2$ once, by REML, and then treats that single number as though it were known when computing everything downstream --- the Hartung-Knapp adjustment is a partial patch for exactly this [@inthout2014hksj]. The Bayesian route puts a prior on $\\mu$ and on $\\tau$ and returns a joint posterior, so uncertainty about how much studies differ is carried through to every number you report. This is the main argument @higgins2009reevaluation make for the approach, and the reason it is standard practice when studies are few [@rover2021weakly].\n\nThree things you get for the trouble:\n\n1. **Honest uncertainty about $\\tau$.** With few studies, $\\tau^2$ is the weakest quantity in a meta-analysis, and the frequentist interval's coverage suffers for it. A posterior gives you an interval for $\\tau$ instead of a point.\n2. **Direct probability statements.** \"There is a 99% probability the risk ratio is below 1\" is a sentence a frequentist analysis cannot produce, and a clinician immediately understands.\n3. **The prediction interval for free.** Draw $\\mu$ and $\\tau$ from the posterior, then draw a new $\\theta_{\\text{new}} \\sim N(\\mu, \\tau^2)$ for each --- and you have the distribution of the true effect in a new setting (@sec-meta-prediction-interval), with no $t$ approximation needed. @higgins2009reevaluation argue this predictive distribution, not the confidence interval for $\\mu$, is the result a random-effects meta-analysis should lead with.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(brms)      # installed by scripts/post_install.sh, not from conda;\nlibrary(metafor)   # needs a working C++ toolchain (see the setup chapter)\n\n# escalc() turns the 2x2 counts into log risk ratios (yi) and their variances\n# (vi); it adds 0.5 to the trial with a zero cell, as metabin() did.\nes <- escalc(measure = \"RR\", ai = ai, n1i = n1i, ci = ci, n2i = n2i,\n             data = dat.egger2001)\nes$sei   <- sqrt(es$vi)\nes$trial <- paste(es$study, es$year)\n\n# yi | se(sei)  -- the outcome is an estimate whose standard error we already\n#                  know, so brms should not try to estimate residual noise\n# (1 | trial)   -- each trial gets its own true effect; the SD of these IS tau\nfit <- brm(\n  yi | se(sei) ~ 1 + (1 | trial),\n  data  = es,\n  prior = c(prior(normal(0, 1),   class = Intercept),  # prior on mu\n            prior(normal(0, 0.5), class = sd)),        # prior on tau (half-normal)\n  chains = 4, iter = 4000, warmup = 1000, seed = 24,\n  control = list(adapt_delta = 0.95)\n)\n\ndraws <- as_draws_df(fit)\nmu  <- draws$b_Intercept            # average log risk ratio\ntau <- draws$sd_trial__Intercept    # between-study SD\n\ncat(sprintf(\"Pooled RR %.3f (95%% CrI %.3f to %.3f)\\n\",\n            exp(median(mu)), exp(quantile(mu, .025)), exp(quantile(mu, .975))))\ncat(sprintf(\"tau       %.3f (95%% CrI %.3f to %.3f)\\n\",\n            median(tau), quantile(tau, .025), quantile(tau, .975)))\ncat(sprintf(\"P(RR < 1) = %.3f   P(RR < 0.9) = %.3f\\n\",\n            mean(mu < 0), mean(mu < log(0.9))))\n\n# Posterior predictive effect in a NEW setting = the prediction interval.\n# One draw of theta_new per posterior draw of (mu, tau), so the interval carries\n# uncertainty about tau rather than fixing it at a point estimate.\nset.seed(24)\ntheta_new <- rnorm(length(mu), mu, tau)\ncat(sprintf(\"New-setting interval: %.3f to %.3f\\n\",\n            exp(quantile(theta_new, .025)), exp(quantile(theta_new, .975))))\n```\n:::\n\n\n**Two notes on the priors**, since they are the only genuinely new decision here.\n\n`normal(0, 1)` on $\\mu$ is on the log scale, so it says the risk ratio is probably somewhere between about 0.14 and 7 --- wide enough to be uninformative about any plausible clinical effect.\n\n`normal(0, 0.5)` on `class = sd` is automatically truncated at zero by brms, making it a **half-normal** prior on $\\tau$ with scale 0.5. That is not an arbitrary choice: the half-normal family is the one generally recommended for $\\tau$ in this model, and for effect measures on a log scale a scale of 0.5 is the specific weakly informative default that @rover2021weakly arrive at --- it puts most of its mass on heterogeneity in the \"reasonable to fairly high\" range and only 4.6% above $\\tau = 1$. It expects some heterogeneity while treating a great deal of it as unlikely. With few studies this prior does real work, and the better move is then an *informative* one drawn from the empirical distribution of $\\tau$ across comparable meta-analyses [@turner2012predicting] rather than any generic default.\n\n**What the code shows.** The Bayesian and frequentist answers land in nearly the same place:\n\n| | Bayesian (brms) | Frequentist (REML + Hartung-Knapp) |\n|---|---|---|\n| Pooled RR | 0.541 (95% CrI 0.347 to 0.781) | 0.511 (95% CI 0.356 to 0.735) |\n| $\\tau$ | 0.459 (95% CrI **0.217 to 0.837**) | 0.476 (point estimate) |\n| Effect in a new setting | 0.168 to 1.537 | 0.171 to 1.526 |\n| $P(\\text{RR} < 1)$ | $> 0.999$ | not available |\n\nLook at the $\\tau$ row: the frequentist analysis reports one number, the Bayesian one reports 0.22 to 0.84. Between-study variation could be half what REML estimated or nearly double it, and *that* is the uncertainty the prediction interval depends on. With sixteen studies the two approaches agree closely, which is the expected result and a good sanity check. With five studies they would not, and the Bayesian version would be the more honest of the two.\n\nBecause the prior on $\\tau$ matters most when it matters at all, refit with a different one and report both:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# A heavier-tailed prior that allows much larger heterogeneity\nfit2 <- update(fit, prior = c(prior(normal(0, 1), class = Intercept),\n                              prior(student_t(3, 0, 1), class = sd)), seed = 24)\n#> Pooled RR 0.530 (95% CrI 0.332 to 0.775), tau 0.500\n```\n:::\n\n\nBarely moves --- with sixteen studies the data, not the prior, is deciding. That sentence is only worth writing because you checked.\n\n::: {.callout-warning}\n## What the Bayesian version does not fix\n\nRead that $P(\\text{RR} < 1) > 0.999$ again. The model is more than 99.9% certain that magnesium reduces mortality after a heart attack.\n\nIt is wrong, and the next section explains why. Priors express uncertainty about *parameters*; they say nothing about studies that were run and never published. Any model --- REML, Hartung-Knapp, Bayesian, whatever comes next --- fitted to a biased set of studies returns a confident, well-calibrated-looking answer about the wrong quantity. **A more careful model is not a substitute for a more complete set of studies.**\n:::\n\n## Small-Study Effects and Non-Reporting Bias {#sec-meta-nonreporting}\n\n::: {.callout-note}\n## A note on terminology\nThis used to be called \"publication bias\". Current Cochrane guidance prefers **non-reporting bias**, because studies go missing for several reasons besides never being published --- selective reporting of outcomes, language restrictions, delayed publication --- and because the funnel plot detects the *symptom* (small-study effects) rather than the *cause* [@cochrane2024handbook].\n:::\n\nStudies with positive, statistically significant results are more likely to be published, published sooner, and published in English. If the unremarkable trials are sitting in a drawer, the evidence you can see is skewed towards good news.\n\n### Funnel plots\n\nA **funnel plot** puts each study's effect estimate on the horizontal axis and its **standard error** on the vertical axis, upside down, so the most precise studies sit at the top.\n\nThat vertical axis is study size in disguise. A standard error shrinks roughly in proportion to $1/\\sqrt{n}$, so a trial with four times as many patients has half the standard error. Big trials therefore have small standard errors and sit near the top of the plot; small trials have large ones and sit near the bottom.\n\n**Why the boundary lines are diagonal.** Suppose every study really is estimating the same effect. A study with standard error SE would then land within roughly $\\pm 1.96 \\times \\text{SE}$ of that common effect 95% of the time. Now read that as you move down the plot: at the very top SE is nearly zero, so the scatter a study is allowed is nearly zero; halfway down, SE is half its largest value, so the allowed scatter is half as wide as at the bottom. The permitted spread grows *in direct proportion to* SE --- and a quantity growing in direct proportion draws a straight line. Two of them, one per side, meeting at the apex: a triangle, or an inverted funnel.\n\nWith no small-study effects, the studies should fill that triangle **symmetrically** --- a tight cluster at the top, fanning out evenly to left and right further down. It is the asymmetry, not the funnel shape itself, that you are looking for.\n\n::: {.panel-tabset}\n\n### R\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# The three reference lines are deliberately styled to be told apart: the funnel\n# edges and the fixed-effect line share a grey dashed look (the funnel is drawn\n# around the fixed-effect estimate), while the random-effects estimate is solid\n# red. ref = NA suppresses meta's no-effect line, which here would sit almost\n# exactly on top of the fixed-effect line (1.006 versus 1.000) and add nothing\n# but confusion.\nfunnel(m,\n  xlab = \"Risk ratio (log scale)\",\n  ylab = \"Standard error (larger trials sit higher up)\",\n  level = 0.95,        # draw the pseudo-95% confidence funnel\n  studlab = FALSE,\n  bg = \"#2c3e50\", col = \"black\",\n  col.common = \"grey50\", lty.common = 2, lwd.common = 1.6,\n  col.random = \"#b02a2a\", lty.random = 1, lwd.random = 1.8,\n  ref = NA\n)\nlegend(\"topleft\", bty = \"n\", cex = 0.8, inset = c(0, 0.03),\n       legend = c(\"Fixed effect (1.01) + 95% funnel\", \"Random effects (0.51)\"),\n       col = c(\"grey50\", \"#b02a2a\"), lty = c(2, 1), lwd = c(1.6, 1.8))\n# Note: funnel() plots on the risk-ratio scale with a log axis, so annotation\n# coordinates are risk ratios, not log risk ratios.\ntext(3.5, 1.30, \"the small trials that\\nfound nothing are\\nnot here\",\n     col = \"grey35\", cex = 0.8, font = 3)\n```\n\n::: {.cell-output-display}\n![Funnel plot of the magnesium trials. Each dot is one trial, plotted by its effect estimate (horizontal) against its standard error (vertical, inverted) --- so the largest trials sit at the top, because more patients means a smaller standard error. The grey dashed diagonals are the pseudo-95% funnel: the range in which trials of a given precision would be expected to scatter *if they were all estimating the same effect*. The grey dashed vertical line is the fixed-effect estimate (1.01) that the funnel is centred on; the solid red line is the random-effects estimate (0.51), and their separation is the same disagreement seen in the table above. Read the bottom of the plot, where the imprecise small trials live: the left side (benefit) is populated and the right side (no benefit) is empty.](meta_analysis_files/figure-html/fig-funnel-magnesium-1.png){#fig-funnel-magnesium fig-align='center' width=100%}\n:::\n:::\n\n\n### Python\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.python .cell-code}\nimport numpy as np\nimport matplotlib.pyplot as plt\n\nse = np.sqrt(var)\nfig, ax = plt.subplots(figsize=(7.5, 5.5))\n\n# The pseudo-95% funnel: +-1.96 SE either side of the fixed-effect estimate,\n# traced down the range of standard errors. This is the line that makes the\n# triangle -- the wider a study's SE, the further it is allowed to scatter.\nse_grid = np.linspace(0.001, se.max() * 1.05, 100)\nax.fill_betweenx(se_grid, te_fe - 1.96 * se_grid, te_fe + 1.96 * se_grid,\n                 color=\"#eff2f5\", zorder=0)\nax.plot(te_fe - 1.96 * se_grid, se_grid, color=\"grey\", lw=1.3, ls=\"--\", zorder=1)\nax.plot(te_fe + 1.96 * se_grid, se_grid, color=\"grey\", lw=1.3, ls=\"--\", zorder=1,\n        label=\"95% funnel around the fixed-effect estimate\")\n\n# Two estimates, styled so they cannot be mistaken for each other or the funnel\nax.axvline(te_fe, color=\"grey\", lw=1.4, ls=\"--\", zorder=2,\n           label=f\"Fixed effect ({np.exp(te_fe):.2f})\")\nax.axvline(te_re, color=\"#b02a2a\", lw=1.8, ls=\"-\", zorder=2,\n           label=f\"Random effects ({np.exp(te_re):.2f})\")\n\nax.scatter(log_rr, se, s=30, color=\"#2c3e50\", zorder=3, label=\"Trials\")\nax.invert_yaxis()                     # most precise (largest) studies at the top\nax.set_xlabel(\"log risk ratio\")\nax.set_ylabel(\"Standard error (larger trials sit higher up)\")\nax.set_title(\"Funnel plot: magnesium trials\")\nax.legend(loc=\"upper left\", frameon=False, fontsize=8)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![The same funnel plot built from scratch with matplotlib. Drawing it by hand shows where the triangle comes from: the funnel edges are simply the fixed-effect estimate plus and minus 1.96 standard errors, evaluated down the range of standard errors present in the data --- a straight line on each side, because the permitted scatter grows in direct proportion to the standard error.](meta_analysis_files/figure-html/fig-funnel-py-1.png){#fig-funnel-py fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\nThe asymmetry is stark. Look at the bottom of the plot, where the imprecise little trials live: the left side (benefit) is populated and the right side (no benefit or harm) is nearly empty. Either small trials of magnesium happened to work much better than large ones, or the small trials that found nothing were never published.\n\n### Testing for asymmetry --- and choosing the right test\n\nYou can turn the eyeball judgement into a number, with two important constraints.\n\n**Constraint one: you need at least 10 studies.** Below that, the tests have too little power to distinguish chance from real asymmetry, and Cochrane advises against using them at all [@cochrane2024handbook]. This threshold is rarely met in practice, so most published meta-analyses cannot legitimately test for asymmetry. Saying \"we could not assess it\" is the correct report, not \"the test was non-significant\".\n\n**Constraint two: the standard test is wrong for some effect measures.** Egger's test regresses the effect estimate on its standard error [@egger1997bias]. For odds ratios and standardised mean differences, the standard error is *mathematically linked* to the size of the effect, which produces funnel-plot asymmetry and small p-values even when nothing is missing. Cochrane therefore recommends the **Harbord** [@harbord2006modified] or **Peters** [@peters2006comparison] tests for binary outcomes instead.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# k = 16, so testing is legitimate here\nfor (test in c(\"Egger\", \"Harbord\", \"Peters\")) {\n  r <- metabias(m, method.bias = test)\n  cat(sprintf(\"%-8s statistic %7.3f   p = %.4f\\n\", test, r$statistic, r$p.value))\n}\n```\n:::\n\n\n**What the code shows.** All three agree emphatically --- Egger p < 0.0001, Harbord p = 0.0001, Peters p = 0.0023. The Peters test is the most conservative of the three, which is the usual pattern and a reason to prefer it when the outcome is binary. When the tests disagree, believe the one appropriate to your effect measure, not the one with the smallest p-value.\n\n::: {.callout-warning}\n## Trim-and-fill: know it, do not lean on it\nYou will meet **trim-and-fill**, which imputes the \"missing\" studies needed to make the funnel symmetric and then re-pools. On these data it adds 8 imputed trials and moves the estimate from RR 0.51 to 0.90 (95% CI 0.52 to 1.54) --- in this case, closer to the truth.\n\nDo not take that as an endorsement. Trim-and-fill assumes one specific mechanism for why studies are missing, it does not estimate what the absent studies actually found, and it is **not among the methods in current Cochrane guidance** [@cochrane2024handbook]. Treat it as a sensitivity analysis that shows how fragile the pooled estimate is, never as a bias-corrected result.\n:::\n\n### What actually happened\n\nThe historical answer is known, and it is why this dataset is worth your time.\n\nThe first seven trials were pooled in the early 1990s, then combined with LIMIT-2 (1,159 patients) in a 1993 meta-analysis that concluded magnesium was an effective, cheap treatment for acute myocardial infarction. Some clinicians adopted it.\n\nThen **ISIS-4** reported: 58,050 randomised patients, the largest trial in the set, and a mortality risk ratio of **1.055** --- no benefit, if anything slight harm [@isis4].\n\nThe small trials were wrong. A meta-analysis of them was confidently, publishably wrong, and the funnel plot in @fig-funnel-magnesium was visible years before ISIS-4 reported. The lesson is not that meta-analysis is untrustworthy; it is that **a pooled estimate is only as good as the set of studies you can see**, and that the diagnostics in this chapter exist because that set is often incomplete.\n\nEverything in the standard analysis pointed at this, if you read it properly: a fixed-versus-random gap of 1.006 versus 0.511, a prediction interval crossing 1, and three asymmetry tests with p < 0.01.\n\n## Reporting a Meta-Analysis\n\nFollow **PRISMA 2020** [@page2021prisma] for the review: the 27-item checklist, the flow diagram of records screened and excluded, and a pre-registered protocol (PROSPERO).\n\nFor the analysis itself, report these four things together. A pooled estimate on its own is not interpretable:\n\n1. **The pooled effect with its confidence interval**, and which model produced it.\n2. **$\\tau^2$ (or $\\tau$) and the prediction interval.** Not just $I^2$ --- see @sec-meta-heterogeneity.\n3. **The methods you chose and why**: the $\\tau^2$ estimator, the confidence-interval method, and how you handled zero cells.\n4. **What you could and could not assess.** If you had fewer than 10 studies, say that you could not evaluate small-study effects, rather than reporting a non-significant test.\n\nCertainty of evidence is usually summarised with **GRADE**, which downgrades for risk of bias, inconsistency (heterogeneity), indirectness, imprecision, and publication bias. Most clinical journals now expect a GRADE summary-of-findings table alongside the meta-analysis; it is a separate skill from the statistics and worth learning from the GRADE handbook directly.\n\n## Where to Go Next {#sec-meta-next-steps}\n\nThis chapter deliberately stops at aggregate-data meta-analysis of one comparison. The methods below are each a chapter in their own right; here is what they are for and where to start.\n\n| Method | The question it answers | Where to start |\n|---|---|---|\n| **Network meta-analysis** | Which of several treatments is best, when few have been compared head to head? Combines direct and indirect evidence. | `netmeta` in R; @salanti2012network. Check the network is connected and that transitivity is plausible before believing any ranking. |\n| **Individual participant data (IPD) meta-analysis** | *Who* benefits? Needs raw patient-level data from each study, which avoids the ecological fallacy. | @riley2019prognostic, @riley2020ipdinteractions; one-stage mixed models or two-stage pooling. |\n| **Bayesian meta-analysis** (covered in @sec-meta-bayesian) | The same random-effects model, but with a prior on $\\tau$ --- which is what you want when there are too few studies to estimate heterogeneity well. | `bayesmeta` in R is a lighter alternative to the `brms` fit shown above; for informative priors on $\\tau$, see @turner2012predicting. |\n| **Dose-response meta-analysis** | Is there a gradient rather than a yes/no effect? | `dosresmeta` in R. |\n| **Prognostic and prediction-model reviews** | Does a published model work elsewhere? | @riley2019prognostic; connects directly to @sec-performance-validation. |\n\nFor everything in this chapter, @harrer2021doing is the best free code-first companion and goes considerably deeper than we do here.\n\n## Exercises\n\n::: {.callout-tip title=\"Exercise 1: Fixed versus random effects, and why it mattered\"}\n\nLoad `dat.egger2001` from `metafor` and reproduce the core analysis.\n\na) Pool the sixteen trials with a fixed-effect and then a random-effects model (REML, Hartung-Knapp interval). Report both risk ratios.\nb) Compute each trial's *percentage weight* under each model. How much weight does ISIS-4 carry under each, and why does it change so much?\nc) Report $\\tau^2$, $I^2$, and the prediction interval. Which of the three tells a clinician how much the effect varies between settings?\nd) In one sentence each, write what you would tell a guideline committee based on (i) the fixed-effect result alone and (ii) the random-effects result alone.\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\n::: {.panel-tabset}\n#### R\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# =============================================================================\n# Chapter 18 - Exercise 1: Fixed versus random effects, and why it mattered\n# Intravenous magnesium after acute myocardial infarction (16 trials)\n# =============================================================================\n#\n# Libraries -------------------------------------------------------------------\nlibrary(meta)     # metabin()\nlibrary(metafor)  # the dat.egger2001 dataset\nlibrary(tidyverse)\n\nd <- dat.egger2001\n\n# Note: in this dataset the control-arm event count is called `ci`, which reads\n# confusingly next to \"confidence interval\". It is deaths in the control arm.\nm <- metabin(\n  event.e = ai, n.e = n1i,     # deaths / patients on magnesium\n  event.c = ci, n.c = n2i,     # deaths / patients on control\n  studlab = paste(study, year),\n  data = d,\n  sm = \"RR\",\n  method.tau = \"REML\",         # REML rather than DerSimonian-Laird\n  method.random.ci = \"HK\",     # Hartung-Knapp-Sidik-Jonkman interval\n  prediction = TRUE\n)\n\nrr <- function(x) exp(x)\n\n# -----------------------------------------------------------------------------\n# (a) Both models\n# -----------------------------------------------------------------------------\ncat(\"=== (a) Fixed-effect vs random-effects ===\\n\")\ncat(sprintf(\"Fixed effect   RR = %.3f (95%% CI %.3f to %.3f)\\n\",\n            rr(m$TE.common), rr(m$lower.common), rr(m$upper.common)))\ncat(sprintf(\"Random effects RR = %.3f (95%% CI %.3f to %.3f)\\n\",\n            rr(m$TE.random), rr(m$lower.random), rr(m$upper.random)))\ncat(\"\\nSame 16 trials, same outcome. One model says magnesium does nothing;\\n\")\ncat(\"the other says it roughly halves mortality.\\n\")\n\n# -----------------------------------------------------------------------------\n# (b) Where did the weight go?\n# -----------------------------------------------------------------------------\nw <- tibble(\n  trial = m$studlab,\n  n = d$n1i + d$n2i,\n  fixed_pct = 100 * m$w.common / sum(m$w.common),\n  random_pct = 100 * m$w.random / sum(m$w.random)\n) |>\n  arrange(desc(n))\n\ncat(\"\\n=== (b) Percentage weight under each model ===\\n\")\nprint(as.data.frame(w |> mutate(across(ends_with(\"pct\"), \\(x) round(x, 1)))),\n      row.names = FALSE)\n\nisis <- w |> filter(str_detect(trial, \"ISIS\"))\ncat(sprintf(\n  \"\\nISIS-4 has %.0f%% of all the patients but carries %.1f%% of the weight under\\n\",\n  100 * isis$n / sum(w$n), isis$fixed_pct\n))\ncat(sprintf(\"the fixed-effect model and only %.1f%% under random effects.\\n\",\n            isis$random_pct))\ncat(\"\\nWhy: random-effects weights are 1 / (within-study variance + tau^2).\\n\")\ncat(\"ISIS-4's within-study variance is tiny, so adding tau^2 = \", round(m$tau2, 3),\n    \"\\nswamps it and its weight collapses. A small trial's variance is already\\n\")\ncat(\"large, so the same addition barely changes it. The effect is to level the\\n\")\ncat(\"weights -- which hands the analysis to the 13 small trials.\\n\")\n\n# -----------------------------------------------------------------------------\n# (c) Heterogeneity: three statistics, three different questions\n# -----------------------------------------------------------------------------\ncat(\"\\n=== (c) Heterogeneity ===\\n\")\ncat(sprintf(\"tau^2 = %.3f  (tau = %.3f on the log-RR scale)\\n\", m$tau2, sqrt(m$tau2)))\ncat(sprintf(\"I^2   = %.1f%%   Q test p = %.4f\\n\", 100 * m$I2, m$pval.Q))\ncat(sprintf(\"Prediction interval: %.3f to %.3f\\n\",\n            rr(m$lower.predict), rr(m$upper.predict)))\ncat(\"\\nThe PREDICTION INTERVAL is the one that answers 'how much does the effect\\n\")\ncat(\"vary between settings'. I^2 is a ratio -- the share of the observed scatter\\n\")\ncat(\"that is real rather than sampling noise -- and would rise if you simply ran\\n\")\ncat(\"the same trials with more patients each. Note that the prediction interval\\n\")\ncat(\"INCLUDES 1, while the confidence interval does not.\\n\")\n\n# -----------------------------------------------------------------------------\n# (d) What you would tell a guideline committee\n# -----------------------------------------------------------------------------\ncat(\"\\n=== (d) Two one-sentence summaries ===\\n\")\ncat(\"(i)  Fixed effect only: \\\"Pooling 62,607 patients across 16 randomised\\n\")\ncat(\"     trials, intravenous magnesium had no effect on mortality after\\n\")\ncat(\"     myocardial infarction (RR 1.01, 95% CI 0.95 to 1.06).\\\"\\n\\n\")\ncat(\"(ii) Random effects only: \\\"Pooling 16 randomised trials, intravenous\\n\")\ncat(\"     magnesium reduced mortality after myocardial infarction by almost\\n\")\ncat(\"     half (RR 0.51, 95% CI 0.36 to 0.74).\\\"\\n\\n\")\ncat(\"Both sentences are defensible from the same data, which is exactly why you\\n\")\ncat(\"must report both models when they disagree, and why the prediction interval\\n\")\ncat(\"and the funnel plot are not optional extras.\\n\")\n```\n:::\n\n#### Python\n\n::: {.cell layout-align=\"center\"}\n\n```{.python .cell-code}\n# =============================================================================\n# Chapter 18 - Exercise 1: Fixed versus random effects, and why it mattered\n# Intravenous magnesium after acute myocardial infarction (16 trials)\n# =============================================================================\n\n# Libraries -------------------------------------------------------------------\n# pip install numpy pandas scipy\nimport numpy as np\nimport pandas as pd\nfrom scipy import stats\n\n# The 16 magnesium trials (dat.egger2001 in metafor / metadat).\n# ai / n1 = deaths / patients on magnesium; ci / n2 = deaths / patients on control.\nSTUDY = [\"Morton 1984\", \"Rasmussen 1986\", \"Smith 1986\", \"Abraham 1987\",\n         \"Feldstedt 1988\", \"Shechter 1989\", \"Ceremuzynski 1989\", \"Bertschat 1989\",\n         \"Singh 1990\", \"Pereira 1990\", \"Shechter 1991\", \"Golf 1991\",\n         \"Thogersen 1991\", \"LIMIT-2 1992\", \"Shechter 1995\", \"ISIS-4 1995\"]\nai = np.array([1, 9, 2, 1, 10, 1, 1, 0, 6, 1, 2, 5, 4, 90, 4, 2216])\nn1 = np.array([40, 135, 200, 48, 150, 59, 25, 22, 76, 27, 89, 23, 130, 1159, 107, 29011])\nci = np.array([2, 23, 7, 1, 8, 9, 3, 1, 11, 7, 12, 13, 8, 118, 17, 2103])\nn2 = np.array([36, 135, 200, 46, 148, 56, 23, 21, 75, 27, 80, 33, 122, 1157, 108, 29039])\n\n\ndef effect_sizes(ai, n1, ci, n2):\n    \"\"\"Log risk ratios and variances; 0.5 added only to trials with a zero cell.\"\"\"\n    incr = np.where((ai == 0) | (ci == 0), 0.5, 0.0)\n    a, c = ai + incr, ci + incr\n    b, d = n1 - ai + incr, n2 - ci + incr\n    log_rr = np.log((a / (a + b)) / (c / (c + d)))\n    var = 1 / a - 1 / (a + b) + 1 / c - 1 / (c + d)\n    return log_rr, var\n\n\ndef pool(log_rr, var):\n    \"\"\"Fixed-effect and DerSimonian-Laird random effects, with an HKSJ interval.\"\"\"\n    k = len(log_rr)\n    w_fe = 1 / var\n    te_fe = np.sum(w_fe * log_rr) / np.sum(w_fe)\n    se_fe = np.sqrt(1 / np.sum(w_fe))\n\n    Q = np.sum(w_fe * (log_rr - te_fe) ** 2)\n    C = np.sum(w_fe) - np.sum(w_fe ** 2) / np.sum(w_fe)\n    tau2 = max(0.0, (Q - (k - 1)) / C)\n    I2 = max(0.0, (Q - (k - 1)) / Q)\n\n    w_re = 1 / (var + tau2)\n    te_re = np.sum(w_re * log_rr) / np.sum(w_re)\n    q_hk = np.sum(w_re * (log_rr - te_re) ** 2) / (k - 1)\n    se_hk = np.sqrt(q_hk / np.sum(w_re))\n\n    return dict(k=k, w_fe=w_fe, w_re=w_re, te_fe=te_fe, se_fe=se_fe, te_re=te_re,\n                se_hk=se_hk, tau2=tau2, I2=I2, Q=Q,\n                Q_p=1 - stats.chi2.cdf(Q, k - 1))\n\n\ndef prediction_interval(res):\n    se = np.sqrt(res[\"se_hk\"] ** 2 + res[\"tau2\"])\n    t = stats.t.ppf(0.975, res[\"k\"] - 2)\n    return np.exp(res[\"te_re\"] - t * se), np.exp(res[\"te_re\"] + t * se)\n\n\nlog_rr, var = effect_sizes(ai, n1, ci, n2)\nres = pool(log_rr, var)\nt_crit = stats.t.ppf(0.975, res[\"k\"] - 1)\n\n# -----------------------------------------------------------------------------\n# (a) Both models\n# -----------------------------------------------------------------------------\nprint(\"=== (a) Fixed-effect vs random-effects ===\")\nprint(f\"Fixed effect   RR = {np.exp(res['te_fe']):.3f} \"\n      f\"(95% CI {np.exp(res['te_fe'] - 1.96 * res['se_fe']):.3f} to \"\n      f\"{np.exp(res['te_fe'] + 1.96 * res['se_fe']):.3f})\")\nprint(f\"Random effects RR = {np.exp(res['te_re']):.3f} \"\n      f\"(95% CI {np.exp(res['te_re'] - t_crit * res['se_hk']):.3f} to \"\n      f\"{np.exp(res['te_re'] + t_crit * res['se_hk']):.3f})\")\nprint(\"\\nSame 16 trials, same outcome. One model says magnesium does nothing;\")\nprint(\"the other says it roughly halves mortality.\")\nprint(\"\\n(These differ slightly from the R solution, which uses Mantel-Haenszel for\")\nprint(\"the fixed-effect estimate and REML for tau-squared. See the chapter note on\")\nprint(\"reconciling the two.)\")\n\n# -----------------------------------------------------------------------------\n# (b) Where did the weight go?\n# -----------------------------------------------------------------------------\nweights = pd.DataFrame({\n    \"trial\": STUDY,\n    \"n\": n1 + n2,\n    \"fixed_pct\": 100 * res[\"w_fe\"] / res[\"w_fe\"].sum(),\n    \"random_pct\": 100 * res[\"w_re\"] / res[\"w_re\"].sum(),\n}).sort_values(\"n\", ascending=False)\n\nprint(\"\\n=== (b) Percentage weight under each model ===\")\nprint(weights.round(1).to_string(index=False))\n\nisis = weights.iloc[0]\nprint(f\"\\nISIS-4 holds {100 * isis['n'] / weights['n'].sum():.0f}% of all patients, \"\n      f\"{isis['fixed_pct']:.1f}% of the fixed-effect weight,\")\nprint(f\"and only {isis['random_pct']:.1f}% of the random-effects weight.\")\nprint(f\"\\nWhy: random-effects weights are 1 / (within-study variance + tau^2).\")\nprint(f\"ISIS-4's within-study variance is tiny, so adding tau^2 = {res['tau2']:.3f}\")\nprint(\"swamps it and its weight collapses. A small trial's variance is already\")\nprint(\"large, so the same addition barely changes it. The effect is to level the\")\nprint(\"weights -- which hands the analysis to the 13 small trials.\")\n\n# -----------------------------------------------------------------------------\n# (c) Heterogeneity\n# -----------------------------------------------------------------------------\npi_lo, pi_hi = prediction_interval(res)\nprint(\"\\n=== (c) Heterogeneity ===\")\nprint(f\"tau^2 = {res['tau2']:.3f} (tau = {np.sqrt(res['tau2']):.3f} on the log-RR scale)\")\nprint(f\"I^2 = {100 * res['I2']:.1f}%   Q = {res['Q']:.1f}, p = {res['Q_p']:.4f}\")\nprint(f\"Prediction interval: {pi_lo:.3f} to {pi_hi:.3f}\")\nprint(\"\\nThe PREDICTION INTERVAL answers 'how much does the effect vary between\")\nprint(\"settings'. I^2 is a ratio -- the share of observed scatter that is real\")\nprint(\"rather than sampling noise -- and would rise if you simply ran the same\")\nprint(\"trials with more patients each. Note that the prediction interval includes\")\nprint(\"1 while the confidence interval does not.\")\n\n# -----------------------------------------------------------------------------\n# (d) What you would tell a guideline committee\n# -----------------------------------------------------------------------------\nprint(\"\\n=== (d) Two one-sentence summaries ===\")\nprint('(i)  Fixed effect only: \"Pooling 62,607 patients across 16 randomised')\nprint('     trials, intravenous magnesium had no effect on mortality after')\nprint('     myocardial infarction.\"')\nprint('(ii) Random effects only: \"Pooling 16 randomised trials, intravenous')\nprint('     magnesium reduced mortality after myocardial infarction by almost')\nprint('     half.\"')\nprint(\"\\nBoth are defensible from the same data, which is why you must report both\")\nprint(\"models when they disagree, and why the prediction interval and the funnel\")\nprint(\"plot are not optional extras.\")\n```\n:::\n\n:::\n:::\n\n:::\n\n::: {.callout-tip title=\"Exercise 2: Meta-analysis from scratch\"}\n\nImplement inverse-variance pooling yourself, without a meta-analysis package, and check it against one.\n\na) From the 2x2 counts, compute each trial's log risk ratio and its variance. Handle the trial with a zero cell explicitly and say what you did.\nb) Compute the fixed-effect pooled estimate and its standard error.\nc) Compute $\\tau^2$ by DerSimonian-Laird, then the random-effects estimate.\nd) Compare your numbers with `metabin(..., method.tau = \"DL\")`. They should agree to three decimal places. Then switch to REML and explain why the answer moves.\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\n::: {.panel-tabset}\n#### R\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# =============================================================================\n# Chapter 18 - Exercise 2: Meta-analysis from scratch\n# Inverse-variance pooling by hand, checked against the meta package\n# =============================================================================\n#\n# Libraries -------------------------------------------------------------------\nlibrary(meta)     # only for the check in part (d)\nlibrary(metafor)  # the dat.egger2001 dataset\n\nd <- dat.egger2001\n\n# -----------------------------------------------------------------------------\n# (a) Log risk ratios and their variances, handling the zero cell\n# -----------------------------------------------------------------------------\n# The log risk ratio and its variance are\n#     log RR = log( (a/(a+b)) / (c/(c+d)) )\n#     Var    = 1/a - 1/(a+b) + 1/c - 1/(c+d)\n# Bertschat 1989 recorded 0 deaths on magnesium. log(0) is undefined and 1/0 is\n# infinite, so that trial cannot be used as it stands. The convention is to add\n# a small continuity increment of 0.5 to the cells of the affected trial only --\n# NOT to every trial, which would shift all 16 estimates.\nzero_cell <- d$ai == 0 | d$ci == 0\ncat(\"Trials with a zero cell:\", paste(d$study[zero_cell], collapse = \", \"), \"\\n\\n\")\n\nincr <- ifelse(zero_cell, 0.5, 0)\na <- d$ai + incr\nb <- d$n1i - d$ai + incr\nc_ <- d$ci + incr\ndd <- d$n2i - d$ci + incr\n\nlog_rr <- log((a / (a + b)) / (c_ / (c_ + dd)))\nv <- 1 / a - 1 / (a + b) + 1 / c_ - 1 / (c_ + dd)\n\ncat(\"=== (a) First few trials ===\\n\")\nprint(data.frame(trial = paste(d$study, d$year), log_rr = round(log_rr, 3),\n                 var = round(v, 4), se = round(sqrt(v), 3))[1:5, ],\n      row.names = FALSE)\n\n# -----------------------------------------------------------------------------\n# (b) Fixed-effect pooled estimate\n# -----------------------------------------------------------------------------\nw_fe <- 1 / v\nte_fe <- sum(w_fe * log_rr) / sum(w_fe)\nse_fe <- sqrt(1 / sum(w_fe))\n\ncat(sprintf(\"\\n=== (b) Fixed effect (inverse variance) ===\\n\"))\ncat(sprintf(\"log RR = %+.4f (SE %.4f)  ->  RR = %.3f (95%% CI %.3f to %.3f)\\n\",\n            te_fe, se_fe, exp(te_fe),\n            exp(te_fe - 1.96 * se_fe), exp(te_fe + 1.96 * se_fe)))\n\n# -----------------------------------------------------------------------------\n# (c) tau^2 by DerSimonian-Laird, then the random-effects estimate\n# -----------------------------------------------------------------------------\nk <- length(log_rr)\nQ <- sum(w_fe * (log_rr - te_fe)^2)\nC <- sum(w_fe) - sum(w_fe^2) / sum(w_fe)\ntau2_dl <- max(0, (Q - (k - 1)) / C)\nI2 <- max(0, (Q - (k - 1)) / Q)\n\nw_re <- 1 / (v + tau2_dl)\nte_re <- sum(w_re * log_rr) / sum(w_re)\nse_re <- sqrt(1 / sum(w_re))\n\ncat(sprintf(\"\\n=== (c) Random effects (DerSimonian-Laird) ===\\n\"))\ncat(sprintf(\"Q = %.2f on %d df, p = %.4f\\n\", Q, k - 1, pchisq(Q, k - 1, lower.tail = FALSE)))\ncat(sprintf(\"tau^2 = %.4f | I^2 = %.1f%%\\n\", tau2_dl, 100 * I2))\ncat(sprintf(\"log RR = %+.4f  ->  RR = %.3f (95%% CI %.3f to %.3f)\\n\",\n            te_re, exp(te_re),\n            exp(te_re - 1.96 * se_re), exp(te_re + 1.96 * se_re)))\n\n# -----------------------------------------------------------------------------\n# (d) Check against the package, then switch to REML\n# -----------------------------------------------------------------------------\n# metabin() defaults to Mantel-Haenszel for the fixed-effect estimate with binary\n# outcomes, so ask for \"Inverse\" to match what we just computed by hand.\nchk_dl <- metabin(ai, n1i, ci, n2i, data = d, sm = \"RR\",\n                  method = \"Inverse\", method.tau = \"DL\")\nchk_reml <- metabin(ai, n1i, ci, n2i, data = d, sm = \"RR\",\n                    method = \"Inverse\", method.tau = \"REML\")\n\ncat(\"\\n=== (d) Hand calculation vs metabin() ===\\n\")\ncmp <- data.frame(\n  quantity = c(\"fixed-effect RR\", \"random-effects RR\", \"tau^2\"),\n  by_hand = round(c(exp(te_fe), exp(te_re), tau2_dl), 4),\n  metabin_DL = round(c(exp(chk_dl$TE.common), exp(chk_dl$TE.random), chk_dl$tau2), 4)\n)\ncmp$agrees <- ifelse(abs(cmp$by_hand - cmp$metabin_DL) < 5e-4, \"yes\", \"NO\")\nprint(cmp, row.names = FALSE)\n\ncat(sprintf(\"\\nSwitching to REML: tau^2 goes from %.4f (DL) to %.4f (REML),\\n\",\n            chk_dl$tau2, chk_reml$tau2))\ncat(sprintf(\"and the random-effects RR from %.3f to %.3f.\\n\",\n            exp(chk_dl$TE.random), exp(chk_reml$TE.random)))\ncat(\"\\nWhy it moves: DerSimonian-Laird is a moment estimator and is known to\\n\")\ncat(\"UNDERESTIMATE the between-study variance, particularly with few studies or\\n\")\ncat(\"very unequal study sizes (Veroniki et al. 2016). A larger tau^2 levels the\\n\")\ncat(\"weights further, so the pooled estimate moves further towards the small\\n\")\ncat(\"trials, and the prediction interval widens. REML (or Paule-Mandel) is the\\n\")\ncat(\"current recommendation; DL survives mainly because it was the default for\\n\")\ncat(\"thirty years and needs no iteration.\\n\")\n```\n:::\n\n#### Python\n\n::: {.cell layout-align=\"center\"}\n\n```{.python .cell-code}\n# =============================================================================\n# Chapter 18 - Exercise 2: Meta-analysis from scratch\n# Inverse-variance pooling by hand, then reconciled with the meta package\n# =============================================================================\n\n# Libraries -------------------------------------------------------------------\n# pip install numpy pandas scipy\nimport numpy as np\nimport pandas as pd\nfrom scipy import stats\n\n# The 16 magnesium trials (dat.egger2001 in metafor / metadat).\n# ai / n1 = deaths / patients on magnesium; ci / n2 = deaths / patients on control.\nSTUDY = [\"Morton 1984\", \"Rasmussen 1986\", \"Smith 1986\", \"Abraham 1987\",\n         \"Feldstedt 1988\", \"Shechter 1989\", \"Ceremuzynski 1989\", \"Bertschat 1989\",\n         \"Singh 1990\", \"Pereira 1990\", \"Shechter 1991\", \"Golf 1991\",\n         \"Thogersen 1991\", \"LIMIT-2 1992\", \"Shechter 1995\", \"ISIS-4 1995\"]\nai = np.array([1, 9, 2, 1, 10, 1, 1, 0, 6, 1, 2, 5, 4, 90, 4, 2216])\nn1 = np.array([40, 135, 200, 48, 150, 59, 25, 22, 76, 27, 89, 23, 130, 1159, 107, 29011])\nci = np.array([2, 23, 7, 1, 8, 9, 3, 1, 11, 7, 12, 13, 8, 118, 17, 2103])\nn2 = np.array([36, 135, 200, 46, 148, 56, 23, 21, 75, 27, 80, 33, 122, 1157, 108, 29039])\n\n\ndef effect_sizes(ai, n1, ci, n2):\n    \"\"\"Log risk ratios and variances; 0.5 added only to trials with a zero cell.\"\"\"\n    incr = np.where((ai == 0) | (ci == 0), 0.5, 0.0)\n    a, c = ai + incr, ci + incr\n    b, d = n1 - ai + incr, n2 - ci + incr\n    log_rr = np.log((a / (a + b)) / (c / (c + d)))\n    var = 1 / a - 1 / (a + b) + 1 / c - 1 / (c + d)\n    return log_rr, var\n\n\ndef pool(log_rr, var):\n    \"\"\"Fixed-effect and DerSimonian-Laird random effects, with an HKSJ interval.\"\"\"\n    k = len(log_rr)\n    w_fe = 1 / var\n    te_fe = np.sum(w_fe * log_rr) / np.sum(w_fe)\n    se_fe = np.sqrt(1 / np.sum(w_fe))\n\n    Q = np.sum(w_fe * (log_rr - te_fe) ** 2)\n    C = np.sum(w_fe) - np.sum(w_fe ** 2) / np.sum(w_fe)\n    tau2 = max(0.0, (Q - (k - 1)) / C)\n    I2 = max(0.0, (Q - (k - 1)) / Q)\n\n    w_re = 1 / (var + tau2)\n    te_re = np.sum(w_re * log_rr) / np.sum(w_re)\n    q_hk = np.sum(w_re * (log_rr - te_re) ** 2) / (k - 1)\n    se_hk = np.sqrt(q_hk / np.sum(w_re))\n\n    return dict(k=k, w_fe=w_fe, w_re=w_re, te_fe=te_fe, se_fe=se_fe, te_re=te_re,\n                se_hk=se_hk, tau2=tau2, I2=I2, Q=Q,\n                Q_p=1 - stats.chi2.cdf(Q, k - 1))\n\n\ndef prediction_interval(res):\n    se = np.sqrt(res[\"se_hk\"] ** 2 + res[\"tau2\"])\n    t = stats.t.ppf(0.975, res[\"k\"] - 2)\n    return np.exp(res[\"te_re\"] - t * se), np.exp(res[\"te_re\"] + t * se)\n\n\nlog_rr, var = effect_sizes(ai, n1, ci, n2)\nres = pool(log_rr, var)\n\n# -----------------------------------------------------------------------------\n# (a) Log risk ratios and variances, handling the zero cell\n# -----------------------------------------------------------------------------\n# log RR = log( (a/(a+b)) / (c/(c+d)) ),  Var = 1/a - 1/(a+b) + 1/c - 1/(c+d)\n# Bertschat 1989 recorded 0 deaths on magnesium, so log(0) is undefined and 1/0\n# is infinite. The convention is to add 0.5 to the cells of the AFFECTED TRIAL\n# ONLY -- correcting every trial would shift all 16 estimates, which is a real\n# difference and not a rounding one.\nzero = (ai == 0) | (ci == 0)\nprint(\"Trials with a zero cell:\", [s for s, z in zip(STUDY, zero) if z], \"\\n\")\n\nlog_rr, var = effect_sizes(ai, n1, ci, n2)\nprint(\"=== (a) First few trials ===\")\nprint(pd.DataFrame({\"trial\": STUDY, \"log_rr\": log_rr.round(3),\n                    \"var\": var.round(4), \"se\": np.sqrt(var).round(3)}\n                   ).head().to_string(index=False))\n\n# -----------------------------------------------------------------------------\n# (b) Fixed-effect pooled estimate\n# -----------------------------------------------------------------------------\nw_fe = 1 / var\nte_fe = np.sum(w_fe * log_rr) / np.sum(w_fe)\nse_fe = np.sqrt(1 / np.sum(w_fe))\nprint(\"\\n=== (b) Fixed effect (inverse variance) ===\")\nprint(f\"log RR = {te_fe:+.4f} (SE {se_fe:.4f})  ->  RR = {np.exp(te_fe):.3f} \"\n      f\"(95% CI {np.exp(te_fe - 1.96 * se_fe):.3f} to \"\n      f\"{np.exp(te_fe + 1.96 * se_fe):.3f})\")\n\n# -----------------------------------------------------------------------------\n# (c) tau^2 by DerSimonian-Laird, then random effects\n# -----------------------------------------------------------------------------\nk = len(log_rr)\nQ = np.sum(w_fe * (log_rr - te_fe) ** 2)\nC = np.sum(w_fe) - np.sum(w_fe ** 2) / np.sum(w_fe)\ntau2 = max(0.0, (Q - (k - 1)) / C)\nI2 = max(0.0, (Q - (k - 1)) / Q)\n\nw_re = 1 / (var + tau2)\nte_re = np.sum(w_re * log_rr) / np.sum(w_re)\nse_re = np.sqrt(1 / np.sum(w_re))\n\nprint(\"\\n=== (c) Random effects (DerSimonian-Laird) ===\")\nprint(f\"Q = {Q:.2f} on {k - 1} df, p = {1 - stats.chi2.cdf(Q, k - 1):.4f}\")\nprint(f\"tau^2 = {tau2:.4f} | I^2 = {100 * I2:.1f}%\")\nprint(f\"log RR = {te_re:+.4f}  ->  RR = {np.exp(te_re):.3f} \"\n      f\"(95% CI {np.exp(te_re - 1.96 * se_re):.3f} to \"\n      f\"{np.exp(te_re + 1.96 * se_re):.3f})\")\n\n# -----------------------------------------------------------------------------\n# (d) Checks\n# -----------------------------------------------------------------------------\n# Internal check: with tau^2 = 0 the random-effects estimate must collapse onto\n# the fixed-effect one. If it does not, the weighting code is wrong.\nte_re_zero = np.sum((1 / var) * log_rr) / np.sum(1 / var)\nprint(\"\\n=== (d) Checks ===\")\nprint(\"tau^2 = 0 reproduces the fixed-effect estimate:\",\n      bool(np.isclose(te_re_zero, te_fe)))\nprint(\"\\nAgainst R: metabin(..., method = 'Inverse', method.tau = 'DL') gives\")\nprint(\"fixed 1.014, random 0.530, tau^2 0.174 -- matching the values above to\")\nprint(\"three decimal places. Two defaults must be overridden to get that match:\")\nprint(\"  method     = 'Inverse'   metabin() uses Mantel-Haenszel for binary\")\nprint(\"                          outcomes, which handles sparse cells better\")\nprint(\"  method.tau = 'DL'        metabin() now defaults to REML\")\nprint(\"\\nSwitching R to REML moves tau^2 from 0.174 to 0.227 and the pooled RR from\")\nprint(\"0.530 to 0.511. DerSimonian-Laird is a moment estimator known to\")\nprint(\"UNDERESTIMATE the between-study variance, especially with few studies or\")\nprint(\"very unequal sizes (Veroniki et al. 2016). A larger tau^2 levels the weights\")\nprint(\"further, pulling the estimate towards the small trials and widening the\")\nprint(\"prediction interval. REML or Paule-Mandel is the current recommendation; DL\")\nprint(\"survives because it was the default for thirty years and needs no iteration.\")\n```\n:::\n\n:::\n:::\n\n:::\n\n::: {.callout-tip title=\"Exercise 3: Detecting the problem before the mega-trial\"}\n\nPut yourself in 1993, before ISIS-4 reported.\n\na) Drop ISIS-4 and re-run the random-effects analysis on the remaining 15 trials. What would you have concluded?\nb) Draw the funnel plot for those 15 trials. Is the asymmetry visible without the mega-trial?\nc) Run the Egger, Harbord and Peters tests on the 15. Are they significant? Which should you trust for a binary outcome, and why?\nd) You now have 15 studies, an apparently large benefit, and an asymmetric funnel. Write the two-sentence limitations paragraph you would have put in the 1993 paper.\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\n::: {.panel-tabset}\n#### R\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# =============================================================================\n# Chapter 18 - Exercise 3: Detecting the problem before the mega-trial\n# What the magnesium evidence looked like in 1993, before ISIS-4 reported\n# =============================================================================\n#\n# Libraries -------------------------------------------------------------------\nlibrary(meta)     # metabin(), funnel(), metabias()\nlibrary(metafor)  # the dat.egger2001 dataset\n\nd <- dat.egger2001\npre <- subset(d, study != \"ISIS-4\")   # the 15 trials available before 1995\n\ncat(\"Trials available pre-ISIS-4:\", nrow(pre),\n    \"| total patients:\", sum(pre$n1i + pre$n2i), \"\\n\")\ncat(\"Largest of them:\", pre$study[which.max(pre$n1i + pre$n2i)],\n    \"with\", max(pre$n1i + pre$n2i), \"patients\\n\\n\")\n\nfit <- function(data) {\n  metabin(event.e = ai, n.e = n1i, event.c = ci, n.c = n2i,\n          studlab = paste(study, year), data = data, sm = \"RR\",\n          method.tau = \"REML\", method.random.ci = \"HK\", prediction = TRUE)\n}\nm_pre <- fit(pre)\nm_all <- fit(d)\n\n# -----------------------------------------------------------------------------\n# (a) What you would have concluded in 1993\n# -----------------------------------------------------------------------------\ncat(\"=== (a) The 15 trials, random effects ===\\n\")\ncat(sprintf(\"RR = %.3f (95%% CI %.3f to %.3f)\\n\", exp(m_pre$TE.random),\n            exp(m_pre$lower.random), exp(m_pre$upper.random)))\ncat(sprintf(\"tau^2 = %.3f | I^2 = %.1f%%\\n\", m_pre$tau2, 100 * m_pre$I2))\ncat(sprintf(\"Prediction interval: %.3f to %.3f\\n\",\n            exp(m_pre$lower.predict), exp(m_pre$upper.predict)))\ncat(sprintf(\"Fixed effect for comparison: RR = %.3f\\n\", exp(m_pre$TE.common)))\ncat(\"\\nOn this evidence you would have concluded that intravenous magnesium\\n\")\ncat(\"roughly halves mortality after myocardial infarction, and the fixed and\\n\")\ncat(\"random models AGREE, because without ISIS-4 there is no dominant large\\n\")\ncat(\"trial to disagree with the small ones. That agreement is falsely reassuring.\\n\")\ncat(sprintf(\"\\nFor contrast, adding ISIS-4 later moves the fixed-effect estimate from\\n\"))\ncat(sprintf(\"%.3f to %.3f.\\n\", exp(m_pre$TE.common), exp(m_all$TE.common)))\n\n# -----------------------------------------------------------------------------\n# (b) The funnel plot on the 15 trials\n# -----------------------------------------------------------------------------\nfunnel(m_pre, xlab = \"Risk ratio (log scale)\",\n       contour = c(0.9, 0.95, 0.99),\n       col.contour = c(\"grey90\", \"grey80\", \"grey70\"))\ntitle(main = \"Magnesium trials available before ISIS-4 (k = 15)\")\nlegend(\"topright\", c(\"p > 0.10\", \"p < 0.10\", \"p < 0.05\"),\n       fill = c(\"grey90\", \"grey80\", \"grey70\"), bty = \"n\", cex = 0.8)\n\ncat(\"\\n=== (b) Funnel plot ===\\n\")\ncat(\"Yes -- the asymmetry is clearly visible without the mega-trial. The lower\\n\")\ncat(\"LEFT of the funnel (small trials showing benefit) is populated; the lower\\n\")\ncat(\"RIGHT (small trials showing no benefit) is close to empty. The warning sign\\n\")\ncat(\"was available years before ISIS-4 reported.\\n\")\n\n# -----------------------------------------------------------------------------\n# (c) The three asymmetry tests\n# -----------------------------------------------------------------------------\ncat(\"\\n=== (c) Tests for funnel plot asymmetry (k = 15, so testing is allowed) ===\\n\")\nfor (test in c(\"Egger\", \"Harbord\", \"Peters\")) {\n  r <- metabias(m_pre, method.bias = test)\n  if (is.null(r$p.value)) {\n    cat(sprintf(\"  %-8s not performed (too few studies)\\n\", test))\n  } else {\n    cat(sprintf(\"  %-8s statistic %7.3f   p = %.4f\\n\", test, r$statistic, r$p.value))\n  }\n}\nharbord_p <- metabias(m_pre, method.bias = \"Harbord\")$p.value\n\ncat(\"\\nWhich to trust: the outcome is BINARY (death), so prefer HARBORD or PETERS.\\n\")\ncat(\"Egger's original test regresses the effect estimate on its standard error,\\n\")\ncat(\"and for odds ratios and standardised mean differences those two quantities\\n\")\ncat(\"are mathematically linked, which manufactures asymmetry and p-values that\\n\")\ncat(\"are too small. Harbord's test fixes that correlation; Peters' test is the\\n\")\ncat(\"most conservative of the three. Here all three agree, which is the easy case.\\n\")\n\n# -----------------------------------------------------------------------------\n# (d) The limitations paragraph you should have written in 1993\n# -----------------------------------------------------------------------------\ncat(\"\\n=== (d) A two-sentence limitations paragraph ===\\n\")\ncat(sprintf(\n'\"Fifteen trials totalling only %s patients (the largest randomising %s) suggest\n that intravenous magnesium substantially reduces mortality after myocardial\n infarction (RR %.2f, 95%% CI %.2f to %.2f); however the funnel plot is markedly\n asymmetric (Harbord p = %.3f) and the effect size falls as trial size rises, so\n we cannot exclude that small trials with null results are missing from the\n literature. The prediction interval spans %.2f to %.2f and therefore includes no\n effect, so a large pragmatic trial is needed before magnesium is adopted into\n routine practice.\"\\n',\n  format(sum(pre$n1i + pre$n2i), big.mark = \",\"),\n  format(max(pre$n1i + pre$n2i), big.mark = \",\"),\n  exp(m_pre$TE.random), exp(m_pre$lower.random), exp(m_pre$upper.random),\n  harbord_p, exp(m_pre$lower.predict), exp(m_pre$upper.predict)))\n\ncat(\"\\nThat trial was ISIS-4: 58,050 patients, RR 1.06, no benefit.\\n\")\ncat(\"\\nOne last thing worth noticing about the 1993 evidence:\\n\")\ncat(sprintf(\"  I^2 was only %.1f%% -- 'low heterogeneity' by the conventional bands --\\n\",\n            100 * m_pre$I2))\ncat(\"  and the fixed and random models broadly agreed. Both of the reassurances\\n\")\ncat(\"  people usually look for were present. The two things that were NOT\\n\")\ncat(\"  reassuring were the prediction interval crossing 1 and the asymmetric\\n\")\ncat(\"  funnel, which is precisely why those deserve more attention than I^2.\\n\")\n```\n:::\n\n#### Python\n\n::: {.cell layout-align=\"center\"}\n\n```{.python .cell-code}\n# =============================================================================\n# Chapter 18 - Exercise 3: Detecting the problem before the mega-trial\n# What the magnesium evidence looked like in 1993, before ISIS-4 reported\n\n# Libraries -------------------------------------------------------------------\n# pip install numpy pandas scipy matplotlib statsmodels\nimport matplotlib.pyplot as plt\nimport statsmodels.api as sm\n\n# Libraries -------------------------------------------------------------------\n# pip install numpy pandas scipy\nimport numpy as np\nimport pandas as pd\nfrom scipy import stats\n\n# The 16 magnesium trials (dat.egger2001 in metafor / metadat).\n# ai / n1 = deaths / patients on magnesium; ci / n2 = deaths / patients on control.\nSTUDY = [\"Morton 1984\", \"Rasmussen 1986\", \"Smith 1986\", \"Abraham 1987\",\n         \"Feldstedt 1988\", \"Shechter 1989\", \"Ceremuzynski 1989\", \"Bertschat 1989\",\n         \"Singh 1990\", \"Pereira 1990\", \"Shechter 1991\", \"Golf 1991\",\n         \"Thogersen 1991\", \"LIMIT-2 1992\", \"Shechter 1995\", \"ISIS-4 1995\"]\nai = np.array([1, 9, 2, 1, 10, 1, 1, 0, 6, 1, 2, 5, 4, 90, 4, 2216])\nn1 = np.array([40, 135, 200, 48, 150, 59, 25, 22, 76, 27, 89, 23, 130, 1159, 107, 29011])\nci = np.array([2, 23, 7, 1, 8, 9, 3, 1, 11, 7, 12, 13, 8, 118, 17, 2103])\nn2 = np.array([36, 135, 200, 46, 148, 56, 23, 21, 75, 27, 80, 33, 122, 1157, 108, 29039])\n\n\ndef effect_sizes(ai, n1, ci, n2):\n    \"\"\"Log risk ratios and variances; 0.5 added only to trials with a zero cell.\"\"\"\n    incr = np.where((ai == 0) | (ci == 0), 0.5, 0.0)\n    a, c = ai + incr, ci + incr\n    b, d = n1 - ai + incr, n2 - ci + incr\n    log_rr = np.log((a / (a + b)) / (c / (c + d)))\n    var = 1 / a - 1 / (a + b) + 1 / c - 1 / (c + d)\n    return log_rr, var\n\n\ndef pool(log_rr, var):\n    \"\"\"Fixed-effect and DerSimonian-Laird random effects, with an HKSJ interval.\"\"\"\n    k = len(log_rr)\n    w_fe = 1 / var\n    te_fe = np.sum(w_fe * log_rr) / np.sum(w_fe)\n    se_fe = np.sqrt(1 / np.sum(w_fe))\n\n    Q = np.sum(w_fe * (log_rr - te_fe) ** 2)\n    C = np.sum(w_fe) - np.sum(w_fe ** 2) / np.sum(w_fe)\n    tau2 = max(0.0, (Q - (k - 1)) / C)\n    I2 = max(0.0, (Q - (k - 1)) / Q)\n\n    w_re = 1 / (var + tau2)\n    te_re = np.sum(w_re * log_rr) / np.sum(w_re)\n    q_hk = np.sum(w_re * (log_rr - te_re) ** 2) / (k - 1)\n    se_hk = np.sqrt(q_hk / np.sum(w_re))\n\n    return dict(k=k, w_fe=w_fe, w_re=w_re, te_fe=te_fe, se_fe=se_fe, te_re=te_re,\n                se_hk=se_hk, tau2=tau2, I2=I2, Q=Q,\n                Q_p=1 - stats.chi2.cdf(Q, k - 1))\n\n\ndef prediction_interval(res):\n    se = np.sqrt(res[\"se_hk\"] ** 2 + res[\"tau2\"])\n    t = stats.t.ppf(0.975, res[\"k\"] - 2)\n    return np.exp(res[\"te_re\"] - t * se), np.exp(res[\"te_re\"] + t * se)\n\n\nlog_rr, var = effect_sizes(ai, n1, ci, n2)\nres = pool(log_rr, var)\n\n# The 15 trials available before ISIS-4 reported in 1995\npre = np.array([s != \"ISIS-4 1995\" for s in STUDY])\nprint(f\"Trials available pre-ISIS-4: {pre.sum()} | \"\n      f\"total patients: {(n1[pre] + n2[pre]).sum():,}\")\nprint(f\"Largest of them: {np.array(STUDY)[pre][np.argmax((n1 + n2)[pre])]} \"\n      f\"with {(n1 + n2)[pre].max():,} patients\\n\")\n\nlog_rr_all, var_all = effect_sizes(ai, n1, ci, n2)\nlog_rr, var = log_rr_all[pre], var_all[pre]\nres = pool(log_rr, var)\nt_crit = stats.t.ppf(0.975, res[\"k\"] - 1)\npi_lo, pi_hi = prediction_interval(res)\n\n# -----------------------------------------------------------------------------\n# (a) What you would have concluded in 1993\n# -----------------------------------------------------------------------------\nprint(\"=== (a) The 15 trials, random effects ===\")\nprint(f\"RR = {np.exp(res['te_re']):.3f} \"\n      f\"(95% CI {np.exp(res['te_re'] - t_crit * res['se_hk']):.3f} to \"\n      f\"{np.exp(res['te_re'] + t_crit * res['se_hk']):.3f})\")\nprint(f\"tau^2 = {res['tau2']:.3f} | I^2 = {100 * res['I2']:.1f}%\")\nprint(f\"Prediction interval: {pi_lo:.3f} to {pi_hi:.3f}\")\nprint(f\"Fixed effect for comparison: RR = {np.exp(res['te_fe']):.3f}\")\nprint(\"\\nYou would have concluded that magnesium roughly halves mortality, and the\")\nprint(\"fixed and random models AGREE -- because without ISIS-4 there is no dominant\")\nprint(\"large trial to disagree with the small ones. That agreement is falsely\")\nprint(\"reassuring.\")\n\n# -----------------------------------------------------------------------------\n# (b) Funnel plot on the 15 trials\n# -----------------------------------------------------------------------------\nse = np.sqrt(var)\nfig, ax = plt.subplots(figsize=(7.5, 5.5))\ngrid = np.linspace(0.001, se.max() * 1.05, 100)\nfor z, shade in [(1.96, \"0.85\"), (2.58, \"0.92\")]:\n    ax.fill_betweenx(grid, res[\"te_fe\"] - z * grid, res[\"te_fe\"] + z * grid,\n                     color=shade, zorder=0)\nax.scatter(log_rr, se, s=30, color=\"#2c3e50\", zorder=3)\nax.axvline(res[\"te_fe\"], color=\"grey\", ls=\"--\", lw=1.2, zorder=2)\nax.axvline(0, color=\"#b02a2a\", lw=1.0, zorder=2)\nax.invert_yaxis()\nax.set_xlabel(\"log risk ratio\")\nax.set_ylabel(\"Standard error (precision increases upwards)\")\nax.set_title(\"Magnesium trials available before ISIS-4 (k = 15)\")\nplt.tight_layout()\nplt.show()\n\nprint(\"\\n=== (b) Funnel plot ===\")\nprint(\"Yes -- the asymmetry is visible without the mega-trial. The lower LEFT\")\nprint(\"(small trials showing benefit) is populated; the lower RIGHT (small trials\")\nprint(\"showing no benefit) is close to empty. The warning sign was available years\")\nprint(\"before ISIS-4 reported.\")\n\n# -----------------------------------------------------------------------------\n# (c) Egger's test, and why it is not the right one here\n# -----------------------------------------------------------------------------\n# Egger's test is a weighted regression of the effect estimate on its standard\n# error; the intercept is what the test looks at.\nX = sm.add_constant(se)\negger = sm.WLS(log_rr, X, weights=1 / var).fit()\nprint(\"\\n=== (c) Egger's test ===\")\nprint(f\"slope on SE = {egger.params[1]:+.3f}, p = {egger.pvalues[1]:.4f}\")\nprint(\"\\nFor a ratio measure the standard error is mathematically linked to the size\")\nprint(\"of the effect, which manufactures asymmetry. Cochrane therefore recommends\")\nprint(\"the Harbord or Peters tests for binary outcomes. Neither has a maintained\")\nprint(\"Python implementation, so run them in R:\")\nprint(\"    metabias(m_pre, method.bias = 'Harbord')   # p = 0.017\")\nprint(\"    metabias(m_pre, method.bias = 'Peters')    # p = 0.043\")\nprint(\"All three agree here, which is the easy case. When they disagree, believe\")\nprint(\"the one appropriate to your effect measure, not the smallest p-value.\")\n\n# -----------------------------------------------------------------------------\n# (d) The limitations paragraph\n# -----------------------------------------------------------------------------\nprint(\"\\n=== (d) A two-sentence limitations paragraph ===\")\nprint(f'\"Fifteen trials totalling only {(n1[pre] + n2[pre]).sum():,} patients (the largest')\nprint(f' randomising {(n1 + n2)[pre].max():,}) suggest that intravenous magnesium substantially')\nprint(f' reduces mortality after myocardial infarction (RR {np.exp(res[\"te_re\"]):.2f}); however the')\nprint(' funnel plot is markedly asymmetric and the effect size falls as trial size')\nprint(' rises, so we cannot exclude that small trials with null results are missing')\nprint(f' from the literature. The prediction interval spans {pi_lo:.2f} to {pi_hi:.2f} and')\nprint(' therefore includes no effect, so a large pragmatic trial is needed before')\nprint(' magnesium is adopted into routine practice.\"')\nprint(\"\\nThat trial was ISIS-4: 58,050 patients, RR 1.06, no benefit.\")\nprint(f\"\\nOne last thing worth noticing: I^2 was only {100 * res['I2']:.1f}% -- 'low\")\nprint(\"heterogeneity' by the conventional bands -- and the two models agreed. Both of\")\nprint(\"the reassurances people usually look for were present. The two that were NOT\")\nprint(\"reassuring were the prediction interval crossing 1 and the asymmetric funnel.\")\n```\n:::\n\n:::\n:::\n\n:::\n\n::: {.callout-tip title=\"Exercise 4: Critical appraisal (Conceptual)\"}\n\nFind a recent meta-analysis in your own field and answer these, in writing:\n\na) How many studies were pooled, and what were the largest and smallest sample sizes? Compute the largest trial's share of the total.\nb) Which model was used, and does the paper report both? If not, can you tell whether it would have mattered?\nc) Is $\\tau^2$ or a prediction interval reported, or only $I^2$? If only $I^2$, what can you and cannot you conclude about how much the effect varies?\nd) Was a funnel plot or asymmetry test reported? Were there at least 10 studies? Was the test appropriate to the effect measure?\ne) Would you change your practice on the strength of this paper? Say what would have to be true for you to change it.\n\n::: {.callout-note collapse=\"true\" title=\"Solution\"}\n::: {.panel-tabset}\n#### R\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# =============================================================================\n# Chapter 18 - Exercise 4: Critical appraisal of a published meta-analysis\n# =============================================================================\n#\n# This is a conceptual exercise: the answer depends on the paper you chose. What\n# follows is (1) a reusable checklist with the reasoning behind each item, and\n# (2) a worked appraisal of the magnesium literature, which is the one paper we\n# can all read the same way.\n#\n# Libraries -------------------------------------------------------------------\nlibrary(meta)\nlibrary(metafor)\n\n# -----------------------------------------------------------------------------\n# The checklist, and why each item is on it\n# -----------------------------------------------------------------------------\n# (a) HOW MANY STUDIES, AND HOW BIG?\n#     Compute the largest study's share of the total sample. If one trial holds\n#     most of the patients, the fixed/random choice will dominate the answer and\n#     the paper must justify it. If every trial is small, ask what is missing.\n#\n# (b) WHICH MODEL, AND ARE BOTH REPORTED?\n#     Random effects is the usual default. The question is whether the paper\n#     reports the fixed-effect result too. If it does not and one trial is much\n#     larger than the rest, you cannot tell whether the choice mattered -- and it\n#     is exactly then that it matters most.\n#\n# (c) IS tau^2 OR A PREDICTION INTERVAL REPORTED, OR ONLY I^2?\n#     I^2 is the PROPORTION of observed scatter that is real rather than sampling\n#     noise. It does not tell you how much the effect varies, and it rises if you\n#     simply run the same trials with more patients each. If only I^2 is given,\n#     you cannot answer \"would this work in my setting?\" at all.\n#\n# (d) WAS ASYMMETRY ASSESSED, AND LEGITIMATELY?\n#     Needs k >= 10. Below that the tests have too little power and Cochrane\n#     advises against them; \"we could not assess it\" is the correct report, not\n#     \"the test was non-significant\". And check the test suits the effect\n#     measure: Egger's test is not appropriate for odds ratios or standardised\n#     mean differences (use Harbord or Peters).\n#\n# (e) WOULD YOU CHANGE PRACTICE?\n#     Force yourself to name the condition. \"I would change if the prediction\n#     interval excluded no effect and the large trials agreed with the small\n#     ones\" is a real answer; \"the result was significant\" is not.\n\n# -----------------------------------------------------------------------------\n# A worked appraisal: the magnesium literature\n# -----------------------------------------------------------------------------\nd <- dat.egger2001\nm <- metabin(event.e = ai, n.e = n1i, event.c = ci, n.c = n2i,\n             studlab = paste(study, year), data = d, sm = \"RR\",\n             method.tau = \"REML\", method.random.ci = \"HK\", prediction = TRUE)\n\nn_tot <- d$n1i + d$n2i\ncat(\"=== (a) Size and spread ===\\n\")\ncat(sprintf(\"k = %d trials, %s patients in total\\n\", m$k, format(sum(n_tot), big.mark = \",\")))\ncat(sprintf(\"smallest %d, largest %s (%.0f%% of all patients)\\n\",\n            min(n_tot), format(max(n_tot), big.mark = \",\"),\n            100 * max(n_tot) / sum(n_tot)))\ncat(\"  -> one trial holds most of the evidence, so the model choice is decisive.\\n\")\n\ncat(\"\\n=== (b) Model choice ===\\n\")\ncat(sprintf(\"fixed effect  RR = %.3f (95%% CI %.3f to %.3f)\\n\",\n            exp(m$TE.common), exp(m$lower.common), exp(m$upper.common)))\ncat(sprintf(\"random effects RR = %.3f (95%% CI %.3f to %.3f)\\n\",\n            exp(m$TE.random), exp(m$lower.random), exp(m$upper.random)))\ncat(\"  -> the two models give opposite conclusions. Reporting only one would be\\n\")\ncat(\"     indefensible here.\\n\")\n\ncat(\"\\n=== (c) Heterogeneity ===\\n\")\ncat(sprintf(\"tau^2 = %.3f | I^2 = %.1f%% | prediction interval %.3f to %.3f\\n\",\n            m$tau2, 100 * m$I2, exp(m$lower.predict), exp(m$upper.predict)))\ncat(\"  -> the prediction interval INCLUDES 1 even though the confidence interval\\n\")\ncat(\"     does not, so a new setting could plausibly see no benefit.\\n\")\n\ncat(\"\\n=== (d) Asymmetry ===\\n\")\ncat(sprintf(\"k = %d, so testing is legitimate (threshold is 10)\\n\", m$k))\nfor (test in c(\"Egger\", \"Harbord\", \"Peters\")) {\n  r <- metabias(m, method.bias = test)\n  cat(sprintf(\"  %-8s p = %.4f%s\\n\", test, r$p.value,\n              if (test == \"Egger\") \"   <- not the right test for a ratio measure\" else \"\"))\n}\ncat(\"  -> strong evidence of small-study effects on all three tests.\\n\")\n\ncat(\"\\n=== (e) Verdict ===\\n\")\ncat(\"No. Three separate signals -- a fixed/random reversal, a prediction interval\\n\")\ncat(\"crossing 1, and a markedly asymmetric funnel -- all say the same thing: the\\n\")\ncat(\"small trials disagree with the large one, and the pooled benefit is an\\n\")\ncat(\"artefact of giving the small trials more weight. What would change my mind:\\n\")\ncat(\"a further large trial agreeing with the small ones, or a mechanism for why\\n\")\ncat(\"effects should genuinely be larger in the settings the small trials studied.\\n\")\ncat(\"\\nHistorically the answer was settled by ISIS-4 (58,050 patients, RR 1.06):\\n\")\ncat(\"no benefit. The appraisal above would have reached the right answer without\\n\")\ncat(\"waiting for it.\\n\")\n```\n:::\n\n#### Python\n\n::: {.cell layout-align=\"center\"}\n\n```{.python .cell-code}\n# =============================================================================\n# Chapter 18 - Exercise 4: Critical appraisal of a published meta-analysis\n#\n# A conceptual exercise: the answer depends on the paper you chose. Below is a\n# reusable checklist with the reasoning behind each item, then a worked appraisal\n# of the magnesium literature, which we can all read the same way.\n# =============================================================================\n\n# Libraries -------------------------------------------------------------------\n# pip install numpy pandas scipy\nimport numpy as np\nimport pandas as pd\nfrom scipy import stats\n\n# The 16 magnesium trials (dat.egger2001 in metafor / metadat).\n# ai / n1 = deaths / patients on magnesium; ci / n2 = deaths / patients on control.\nSTUDY = [\"Morton 1984\", \"Rasmussen 1986\", \"Smith 1986\", \"Abraham 1987\",\n         \"Feldstedt 1988\", \"Shechter 1989\", \"Ceremuzynski 1989\", \"Bertschat 1989\",\n         \"Singh 1990\", \"Pereira 1990\", \"Shechter 1991\", \"Golf 1991\",\n         \"Thogersen 1991\", \"LIMIT-2 1992\", \"Shechter 1995\", \"ISIS-4 1995\"]\nai = np.array([1, 9, 2, 1, 10, 1, 1, 0, 6, 1, 2, 5, 4, 90, 4, 2216])\nn1 = np.array([40, 135, 200, 48, 150, 59, 25, 22, 76, 27, 89, 23, 130, 1159, 107, 29011])\nci = np.array([2, 23, 7, 1, 8, 9, 3, 1, 11, 7, 12, 13, 8, 118, 17, 2103])\nn2 = np.array([36, 135, 200, 46, 148, 56, 23, 21, 75, 27, 80, 33, 122, 1157, 108, 29039])\n\n\ndef effect_sizes(ai, n1, ci, n2):\n    \"\"\"Log risk ratios and variances; 0.5 added only to trials with a zero cell.\"\"\"\n    incr = np.where((ai == 0) | (ci == 0), 0.5, 0.0)\n    a, c = ai + incr, ci + incr\n    b, d = n1 - ai + incr, n2 - ci + incr\n    log_rr = np.log((a / (a + b)) / (c / (c + d)))\n    var = 1 / a - 1 / (a + b) + 1 / c - 1 / (c + d)\n    return log_rr, var\n\n\ndef pool(log_rr, var):\n    \"\"\"Fixed-effect and DerSimonian-Laird random effects, with an HKSJ interval.\"\"\"\n    k = len(log_rr)\n    w_fe = 1 / var\n    te_fe = np.sum(w_fe * log_rr) / np.sum(w_fe)\n    se_fe = np.sqrt(1 / np.sum(w_fe))\n\n    Q = np.sum(w_fe * (log_rr - te_fe) ** 2)\n    C = np.sum(w_fe) - np.sum(w_fe ** 2) / np.sum(w_fe)\n    tau2 = max(0.0, (Q - (k - 1)) / C)\n    I2 = max(0.0, (Q - (k - 1)) / Q)\n\n    w_re = 1 / (var + tau2)\n    te_re = np.sum(w_re * log_rr) / np.sum(w_re)\n    q_hk = np.sum(w_re * (log_rr - te_re) ** 2) / (k - 1)\n    se_hk = np.sqrt(q_hk / np.sum(w_re))\n\n    return dict(k=k, w_fe=w_fe, w_re=w_re, te_fe=te_fe, se_fe=se_fe, te_re=te_re,\n                se_hk=se_hk, tau2=tau2, I2=I2, Q=Q,\n                Q_p=1 - stats.chi2.cdf(Q, k - 1))\n\n\ndef prediction_interval(res):\n    se = np.sqrt(res[\"se_hk\"] ** 2 + res[\"tau2\"])\n    t = stats.t.ppf(0.975, res[\"k\"] - 2)\n    return np.exp(res[\"te_re\"] - t * se), np.exp(res[\"te_re\"] + t * se)\n\n\nlog_rr, var = effect_sizes(ai, n1, ci, n2)\nres = pool(log_rr, var)\n\n# -----------------------------------------------------------------------------\n# The checklist, and why each item is on it\n# -----------------------------------------------------------------------------\n# (a) HOW MANY STUDIES, AND HOW BIG?\n#     Compute the largest study's share of the total sample. If one trial holds\n#     most of the patients, the fixed/random choice decides the answer and the\n#     paper must justify it. If every trial is small, ask what is missing.\n#\n# (b) WHICH MODEL, AND ARE BOTH REPORTED?\n#     Random effects is the usual default; the question is whether the paper also\n#     reports the fixed-effect result. If it does not, and one trial is far larger\n#     than the rest, you cannot tell whether the choice mattered -- and that is\n#     exactly when it matters most.\n#\n# (c) IS tau^2 OR A PREDICTION INTERVAL REPORTED, OR ONLY I^2?\n#     I^2 is the PROPORTION of observed scatter that is real rather than sampling\n#     noise. It does not say how much the effect varies, and it rises if the same\n#     trials are simply run larger. With only I^2 you cannot answer \"would this\n#     work in my setting?\".\n#\n# (d) WAS ASYMMETRY ASSESSED, AND LEGITIMATELY?\n#     Needs k >= 10; below that Cochrane advises against testing, and \"we could\n#     not assess it\" is the correct report rather than \"the test was not\n#     significant\". Check the test suits the effect measure: Egger's test is not\n#     appropriate for odds ratios or standardised mean differences.\n#\n# (e) WOULD YOU CHANGE PRACTICE?\n#     Name the condition. \"I would change if the prediction interval excluded no\n#     effect and the large trials agreed with the small ones\" is a real answer;\n#     \"the result was significant\" is not.\n\n# -----------------------------------------------------------------------------\n# A worked appraisal: the magnesium literature\n# -----------------------------------------------------------------------------\nlog_rr, var = effect_sizes(ai, n1, ci, n2)\nres = pool(log_rr, var)\nn_tot = n1 + n2\npi_lo, pi_hi = prediction_interval(res)\nt_crit = stats.t.ppf(0.975, res[\"k\"] - 1)\n\nprint(\"=== (a) Size and spread ===\")\nprint(f\"k = {res['k']} trials, {n_tot.sum():,} patients in total\")\nprint(f\"smallest {n_tot.min()}, largest {n_tot.max():,} \"\n      f\"({100 * n_tot.max() / n_tot.sum():.0f}% of all patients)\")\nprint(\"  -> one trial holds most of the evidence, so model choice is decisive.\")\n\nprint(\"\\n=== (b) Model choice ===\")\nprint(f\"fixed effect   RR = {np.exp(res['te_fe']):.3f}\")\nprint(f\"random effects RR = {np.exp(res['te_re']):.3f} \"\n      f\"(95% CI {np.exp(res['te_re'] - t_crit * res['se_hk']):.3f} to \"\n      f\"{np.exp(res['te_re'] + t_crit * res['se_hk']):.3f})\")\nprint(\"  -> opposite conclusions. Reporting only one would be indefensible.\")\n\nprint(\"\\n=== (c) Heterogeneity ===\")\nprint(f\"tau^2 = {res['tau2']:.3f} | I^2 = {100 * res['I2']:.1f}% | \"\n      f\"prediction interval {pi_lo:.3f} to {pi_hi:.3f}\")\nprint(\"  -> the prediction interval includes 1 even though the CI does not.\")\n\nprint(f\"\\n=== (d) Asymmetry ===\")\nprint(f\"k = {res['k']}, so testing is legitimate (the threshold is 10). Run the tests\")\nprint(\"in R, where Harbord and Peters are implemented:\")\nprint(\"    Egger   p < 0.001   <- not the right test for a ratio measure\")\nprint(\"    Harbord p = 0.0001\")\nprint(\"    Peters  p = 0.0023\")\nprint(\"  -> strong evidence of small-study effects on all three.\")\n\nprint(\"\\n=== (e) Verdict ===\")\nprint(\"No. Three separate signals -- a fixed/random reversal, a prediction interval\")\nprint(\"crossing 1, and a markedly asymmetric funnel -- all say the same thing: the\")\nprint(\"small trials disagree with the large one, and the pooled benefit is an\")\nprint(\"artefact of giving the small trials more weight. What would change my mind: a\")\nprint(\"further large trial agreeing with the small ones, or a mechanism for why\")\nprint(\"effects should genuinely be larger in the settings the small trials studied.\")\nprint(\"\\nHistorically the question was settled by ISIS-4 (58,050 patients, RR 1.06):\")\nprint(\"no benefit. The appraisal above reaches the right answer without waiting.\")\n```\n:::\n\n:::\n:::\n\n:::\n\n## Summary\n\n| Concept | Key point |\n|---|---|\n| Inverse-variance weighting | More precise studies get more say --- this is where all the trouble starts |\n| Fixed effect | Assumes one true effect; the largest trial dominates |\n| Random effects | Assumes a distribution of true effects; **levels the weights, so small studies gain influence** |\n| $\\tau^2$ | Between-study variance --- how much the true effects genuinely differ |\n| $I^2$ | The *proportion* of scatter that is real. **Not** how much the effect varies |\n| Prediction interval | The range a new study's true effect might fall in. Report it alongside the CI |\n| Cochran's $Q$ | A test for any heterogeneity, not a measure of its size |\n| Bayesian version | The same hierarchical model with priors on $\\mu$ and $\\tau$; gives an interval for $\\tau$ and direct probability statements. Report prior sensitivity |\n| Small-study effects | Effects shrinking as trials get larger; the funnel plot's real subject |\n| Asymmetry tests | Need $k \\ge 10$; use Harbord or Peters for binary outcomes, not Egger |\n| Trim-and-fill | A fragility check, not a correction; not in current Cochrane guidance |\n| Ecological fallacy | Study-level moderators do not license individual-level claims |\n\n::: {.callout-tip}\n## Key Takeaways\n- The **fixed-versus-random choice can change the conclusion completely.** On the magnesium data it is the difference between \"no effect\" (RR 1.01) and \"halves mortality\" (RR 0.51). Report both when they disagree and treat the gap as a finding.\n- **Random effects gives small studies more influence.** That is right when studies genuinely differ and catastrophic when the small studies are biased.\n- **$I^2$ does not tell you how much the effect varies** --- the prediction interval does. The 25/50/75% bands are not a substitute for it.\n- **Read the forest plot for shape, not just for the diamond.** Small studies on one side and large ones on the other is the pattern that has misled clinical practice most often.\n- **Asymmetry tests need at least 10 studies**, and Egger's test is not appropriate for odds ratios or standardised mean differences. If you have fewer than 10, report that you could not assess it.\n- A meta-analysis of the available studies is not the same as a meta-analysis of the evidence. **Magnesium looked like a cheap way to prevent deaths after a heart attack until a trial of 58,050 patients said otherwise.**\n:::\n\n## References and Further Reading\n\n- For systematic review methodology and current guidance on missing evidence, see @cochrane2024handbook; for reporting, see @page2021prisma.\n- For the random-effects model, see @dersimonian1986; for choosing a $\\tau^2$ estimator, see @veroniki2016methods; and for the confidence-interval method, see @inthout2014hksj.\n- For heterogeneity, read @borenstein2024mistakes (or the shorter @borenstein2023heterogeneity) on why $I^2$ is not a measure of how much the effect varies, alongside @higgins2003inconsistency for the original $I^2$ paper.\n- For prediction intervals, see @riley2011interpretation and @inthout2016prediction; for the variants that software actually implements, see @partlett2017random.\n- For Bayesian meta-analysis, start with @higgins2009reevaluation on why the predictive distribution is the quantity of interest and @sutton2001bayesian for the hierarchical-model framing; for priors on between-study heterogeneity, see @rover2021weakly and @turner2012predicting; and @harrer2021doing for further worked `brms` code.\n- For funnel plot asymmetry, see @egger1997bias for the original test and @harbord2006modified and @peters2006comparison for the versions appropriate to binary outcomes.\n- For the running example, see @egger2001systematic for the dataset and @isis4 for the trial that settled the question.\n- For network meta-analysis, see @salanti2012network; for individual participant data, see @riley2019prognostic and @riley2020ipdinteractions.\n- For a code-first companion that goes deeper than this chapter, see @harrer2021doing.\n- For software, see @viechtbauer2010metafor and @schwarzer2015metaR.\n\n::: {.sectionrefs}\n:::\n",
    "supporting": [
      "meta_analysis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}